import type {
  GameTemplate,
  MechanicDefinition,
  TemplateSuggestion,
} from "./types";

const suggestion = (
  id: string,
  category: TemplateSuggestion["category"],
  title: string,
  description: string,
  keeps: string,
  newAssets: string,
  level: TemplateSuggestion["level"],
  risk: TemplateSuggestion["risk"],
): TemplateSuggestion => ({
  id,
  category,
  title,
  description,
  keeps,
  newAssets,
  level,
  risk,
});

const commonSuggestions = (
  id: string,
  core: string,
  content: string,
  mechanic: string,
): TemplateSuggestion[] => [
  suggestion(
    `${id}-world`,
    "world",
    "换一个世界观",
    "替换角色身份、场景设定、目标物和文案包装。",
    core,
    "角色、场景、目标物 AI 位图与界面文案",
    "R0",
    "低",
  ),
  suggestion(
    `${id}-visual`,
    "visual",
    "重做视觉风格",
    "选择一致的美术方向，重新生成封面和游戏内位图资源。",
    core,
    "完整 AI 位图资源包，不使用 SVG 代替游戏美术",
    "R0",
    "低",
  ),
  suggestion(
    `${id}-content`,
    "content",
    "更换内容与节奏",
    content,
    core,
    "关卡数据、内容资源与调节参数",
    "R1",
    "低",
  ),
  suggestion(
    `${id}-mechanic`,
    "mechanic",
    "加入一种小机制",
    mechanic,
    core,
    "一组专属资源、规则合同和自动验收场景",
    "R2",
    "中",
  ),
];

export const GAME_TEMPLATES: GameTemplate[] = [
  {
    id: "falling-blocks",
    name: "落块消行",
    genre: "反应益智",
    pitch: "旋转和移动下落拼块，用完整横行换取生存空间。",
    coreLoop: "观察 → 旋转移动 → 落下 → 消行",
    coreRules: ["拼块持续下落", "完整横行才会消除", "堆到顶部时本局结束"],
    capabilities: ["grid-simulation", "piece-rotation", "line-clear"],
    suggestions: commonSuggestions(
      "falling-blocks",
      "下落、旋转、整行消除和触顶失败保持不变",
      "调整速度档、任务目标、砖块材质和关卡节奏。",
      "只加入垃圾行、限时任务或一种特殊目标中的一项。",
    ),
    redirectExamples: ["自由建造", "角色战斗", "资源经营"],
  },
  {
    id: "picture-puzzle",
    name: "图片拼图",
    genre: "空间拼合",
    pitch: "拖动散落拼块，在清晰反馈中还原完整画面。",
    coreLoop: "观察 → 拖动 → 吸附 → 完成",
    coreRules: ["拼块来源固定", "正确位置会吸附", "全部归位才完成"],
    capabilities: ["drag-snap", "spatial-validation", "progress-save"],
    suggestions: commonSuggestions(
      "picture-puzzle",
      "拖放、正确吸附和全部完成保持不变",
      "调整拼块数量、参考图强度、旋转和图片主题。",
      "只加入限时挑战或分区整理中的一项。",
    ),
    redirectExamples: ["物理战斗", "开放探索", "自由绘画"],
  },
  {
    id: "breakout",
    name: "弹球破阵",
    genre: "街机反应",
    pitch: "移动挡板改变弹球轨迹，清除精心排列的目标。",
    coreLoop: "接球 → 改变角度 → 命中 → 清场",
    coreRules: ["挡板反弹弹球", "弹球命中目标", "清除目标后结算"],
    capabilities: ["arcade-collision", "trajectory", "level-layout"],
    suggestions: commonSuggestions(
      "breakout",
      "挡板反弹、弹球碰撞和清场目标保持不变",
      "替换砖阵、章节主题、球速和挡板手感。",
      "只加入一种特殊砖或一种主动能力。",
    ),
    redirectExamples: ["自由射击", "塔防", "平台动作"],
  },
  {
    id: "sliding-block",
    name: "移块脱困",
    genre: "空间推理",
    pitch: "在有限格位中合法腾挪，让目标块抵达出口。",
    coreLoop: "判断空间 → 移块 → 腾挪 → 脱困",
    coreRules: ["方块占格固定", "移动不能重叠", "目标块必须到达出口"],
    capabilities: ["grid-occupancy", "legal-move", "solver"],
    suggestions: commonSuggestions(
      "sliding-block",
      "固定占格、合法腾挪和目标到出口保持不变",
      "替换题库、步数挑战、提示方式和人物包装。",
      "只加入锁块或单向格中的一项。",
    ),
    redirectExamples: ["自由拖放", "实时追逐", "战斗"],
  },
  {
    id: "maze",
    name: "迷宫探索",
    genre: "路径解谜",
    pitch: "理解空间和阻挡规则，从入口找到可达出口。",
    coreLoop: "探索 → 记忆 → 绕路 → 抵达",
    coreRules: ["墙体不可穿越", "入口与出口连通", "抵达出口后完成"],
    capabilities: ["grid-path", "reachability", "fog-of-war"],
    suggestions: commonSuggestions(
      "maze",
      "连通路径、墙体阻挡和抵达出口保持不变",
      "替换地图包、迷雾强度、检查点和世界观。",
      "只加入钥匙门、冰面或一种地形规则。",
    ),
    redirectExamples: ["开放世界", "生存建造", "多人竞速"],
  },
  {
    id: "snake",
    name: "蜿蜒收集",
    genre: "生存反应",
    pitch: "持续前进并规划转向，用不断增长的身体制造压力。",
    coreLoop: "转向 → 收集 → 增长 → 避免自撞",
    coreRules: ["角色持续移动", "不能立即反向", "收集后增长且自撞失败"],
    capabilities: ["continuous-movement", "body-trail", "pickup"],
    suggestions: commonSuggestions(
      "snake",
      "持续移动、转向限制、增长和自撞失败保持不变",
      "替换生物、食物、场型、速度曲线和阶段目标。",
      "只加入金色食物或一种障碍规则。",
    ),
    redirectExamples: ["射击战斗", "经营养成", "自由停走"],
  },
  {
    id: "merge-2048",
    name: "滑动合成",
    genre: "数字策略",
    pitch: "每次推动整个棋盘，在有限空间里规划合并顺序。",
    coreLoop: "判断 → 全盘滑动 → 合并 → 应对新块",
    coreRules: ["一次输入推动全盘", "同值方块每步只合并一次", "有效移动后生成新块"],
    capabilities: ["grid-slide", "merge-equal", "undo-limited"],
    suggestions: commonSuggestions(
      "merge-2048",
      "全盘滑动、同值一次一并和移动后生成保持不变",
      "替换数字符号、目标、棋盘规模、难度和撤销次数。",
      "只加入一种特殊格或一种任务限制。",
    ),
    redirectExamples: ["单块拖动", "战斗棋盘", "复杂经济"],
  },
  {
    id: "space-shooter",
    name: "波次射击",
    genre: "动作射击",
    pitch: "移动、射击并判断威胁优先级，在波次压力中存活。",
    coreLoop: "预判 → 移动射击 → 命中 → 波次结算",
    coreRules: ["玩家可移动和射击", "命中产生明确反馈", "生命与波次能够结算"],
    capabilities: ["projectile-hit", "enemy-wave", "invulnerability-window"],
    suggestions: commonSuggestions(
      "space-shooter",
      "移动、弹体、命中、波次和生命保持不变",
      "替换敌人包、弹幕节奏、Boss 主题和机体表现。",
      "只加入一种主动能力或一种敌人行为。",
    ),
    redirectExamples: ["经营基地", "开放星图", "实时多人"],
  },
  {
    id: "polyomino",
    name: "轮廓拼块",
    genre: "空间拼合",
    pitch: "旋转多格拼块，在没有重叠的前提下覆盖目标轮廓。",
    coreLoop: "观察 → 旋转 → 试放 → 覆盖",
    coreRules: ["拼块可以旋转", "放置不能重叠", "必须覆盖目标轮廓"],
    capabilities: ["piece-rotation", "shape-fit", "coverage-check"],
    suggestions: commonSuggestions(
      "polyomino",
      "旋转、合法放置、无重叠和覆盖目标保持不变",
      "替换轮廓主题、拼块包、提示和评价目标。",
      "只加入限时挑战或固定块。",
    ),
    redirectExamples: ["自由绘制", "物理堆叠", "战斗"],
  },
  {
    id: "block-placement",
    name: "方块填阵",
    genre: "放置消除",
    pitch: "从三个拼块中选择并放置，用横竖消除维持空间。",
    coreLoop: "三选一 → 放置 → 横竖消除 → 补充",
    coreRules: ["每轮提供三块", "拼块必须合法放置", "横列或竖列填满后消除"],
    capabilities: ["shape-fit", "line-clear", "move-availability"],
    suggestions: commonSuggestions(
      "block-placement",
      "三选拼块、合法放置、横竖消行和无解结束保持不变",
      "替换材质、棋盘主题、连击反馈和旅程节奏。",
      "只加入一种特殊块。",
    ),
    redirectExamples: ["下落方块", "实时对战", "经营"],
  },
  {
    id: "region-logic",
    name: "区域逻辑",
    genre: "逻辑推理",
    pitch: "根据行列、区域和相邻限制逐步排除，得到唯一解。",
    coreLoop: "读取线索 → 排除 → 标记 → 验证",
    coreRules: ["约束信息完整", "题目逻辑可解", "错误能够被解释"],
    capabilities: ["constraint-solver", "hint-explanation", "unique-solution"],
    suggestions: commonSuggestions(
      "region-logic",
      "行列区域约束、逻辑可解和提示解释保持不变",
      "替换符号、版面、题库难度和提示表达。",
      "只加入一种额外逻辑约束。",
    ),
    redirectExamples: ["随机猜测", "实时操作", "战斗"],
  },
  {
    id: "tile-roguelite",
    name: "牌阵旅程",
    genre: "消除构筑",
    pitch: "在可解牌阵和路线选择之间积累协同，完成一次短旅程。",
    coreLoop: "配对消除 → 路线选择 → 获得遗物 → 继续挑战",
    coreRules: ["只有自由牌可以配对", "牌阵必须可解", "路线和遗物会影响本局"],
    capabilities: ["free-tile", "seeded-layout", "route-choice", "relic-synergy"],
    suggestions: commonSuggestions(
      "tile-roguelite",
      "自由牌、成对消除、牌阵可解和路线遗物保持不变",
      "替换牌面世界观、路线事件、遗物和关卡结构。",
      "只加入一类事件或一组遗物协同。",
    ),
    redirectExamples: ["传统麻将对局", "实时战斗", "开放经营"],
  },
  {
    id: "collect-escape-3d",
    name: "立体收集撤离",
    genre: "3D 探索",
    pitch: "在清晰空间中移动和收集，避开危险后抵达出口。",
    coreLoop: "探索 → 收集 → 规避 → 撤离",
    coreRules: ["角色和相机可控", "碰撞边界清楚", "收集目标后可以抵达出口"],
    capabilities: ["character-controller", "camera", "collect-escape", "checkpoint-save"],
    suggestions: commonSuggestions(
      "collect-escape-3d",
      "角色移动、相机、碰撞、收集和出口保持不变",
      "替换世界、角色、收集物、危险物和路线。",
      "只加入一种移动能力或一种动态危险。",
    ),
    redirectExamples: ["开放世界", "载具群", "复杂骨骼战斗"],
  },
  {
    id: "arena-3d",
    name: "立体竞技场",
    genre: "3D 动作",
    pitch: "在有限场地里走位和攻击，识别敌人行为并完成波次。",
    coreLoop: "识别威胁 → 走位 → 攻击 → 波次强化",
    coreRules: ["移动和攻击可响应", "命中判定稳定", "敌人波次能够结算"],
    capabilities: ["character-controller", "melee-hit", "enemy-ai", "enemy-wave"],
    suggestions: commonSuggestions(
      "arena-3d",
      "移动、攻击、命中、敌人 AI 和波次保持不变",
      "替换场景、武器表现、敌人包和强化选项。",
      "只加入一种武器或一种敌人行为。",
    ),
    redirectExamples: ["联机竞技", "大型团战", "持久世界"],
  },
];

export const MECHANIC_LIBRARY: MechanicDefinition[] = [
  {
    id: "lane-dodge",
    name: "路线闪避",
    description: "在少量清晰路线之间快速移动，预判并避开障碍。",
    capabilityIds: ["continuous-movement", "seeded-spawning", "safe-lane"],
    keywords: ["闪避", "躲", "竞速", "跑酷", "路线", "障碍", "速度"],
  },
  {
    id: "grid-merge",
    name: "全盘滑动合成",
    description: "一次输入改变整个棋盘，通过合并管理有限空间。",
    capabilityIds: ["grid-slide", "merge-equal", "move-availability"],
    keywords: ["合成", "数字", "滑动", "棋盘", "方块", "升级"],
  },
  {
    id: "projectile-combat",
    name: "弹体命中",
    description: "移动、发射和命中构成即时反馈明确的动作循环。",
    capabilityIds: ["projectile-hit", "enemy-wave", "invulnerability-window"],
    keywords: ["射击", "子弹", "弹幕", "敌人", "战斗", "Boss"],
  },
  {
    id: "grid-path",
    name: "路径与可达性",
    description: "用墙体、地形和门构成可以验证的空间路线。",
    capabilityIds: ["grid-path", "reachability", "checkpoint-save"],
    keywords: ["迷宫", "探索", "路径", "出口", "钥匙", "地形"],
  },
  {
    id: "route-choice",
    name: "路线三选一",
    description: "让玩家在一次旅程中反复选择风险、奖励和构筑方向。",
    capabilityIds: ["route-choice", "seeded-run", "checkpoint-save"],
    keywords: ["肉鸽", "路线", "选择", "构筑", "遗物", "旅程"],
  },
  {
    id: "collect-escape",
    name: "收集后撤离",
    description: "收集目标会增加收益与风险，完成条件是安全抵达出口。",
    capabilityIds: ["pickup", "risk-reward", "exit-unlock"],
    keywords: ["收集", "撤离", "出口", "宝物", "逃离", "探索"],
  },
  {
    id: "drag-snap",
    name: "拖放吸附",
    description: "直接拖动物体，在合法位置提供清楚的吸附和纠错反馈。",
    capabilityIds: ["drag-snap", "spatial-validation", "touch-input"],
    keywords: ["拖动", "拼图", "摆放", "整理", "拼合", "吸附"],
  },
  {
    id: "constraint-deduction",
    name: "约束推理",
    description: "通过完整线索逐步排除，并能解释提示和错误原因。",
    capabilityIds: ["constraint-solver", "unique-solution", "hint-explanation"],
    keywords: ["推理", "逻辑", "数独", "谜题", "唯一解", "排除"],
  },
  {
    id: "queue-management",
    name: "队列经营",
    description: "在有限时间与容量内安排订单队列，让等待、加工和交付形成可预测的经营循环。",
    capabilityIds: ["queue-scheduling", "order-deadline", "capacity-upgrade", "round-progression"],
    keywords: ["经营", "店铺", "订单", "排队", "制作", "顾客", "时间管理"],
  },
  {
    id: "chapter-branch",
    name: "章节选择",
    description: "通过短篇章节、有限选择和状态标记产生可回看、可恢复的分支结果。",
    capabilityIds: ["chapter-state", "branch-choice", "consequence-flag", "checkpoint-save"],
    keywords: ["剧情", "故事", "对话", "章节", "分支", "结局", "选择"],
  },
  {
    id: "deck-combo",
    name: "卡组协同",
    description: "抽取、消耗和组合卡牌形成资源取舍，并以可复现牌库验证协同效果。",
    capabilityIds: ["seeded-deck", "card-cost", "combo-resolution", "turn-progression"],
    keywords: ["卡牌", "卡组", "抽牌", "费用", "连携", "协同", "回合"],
  },
  {
    id: "gamepad-control",
    name: "手柄操作",
    description: "为单人核心动作增加手柄等价输入、焦点反馈和断开后的键盘回退。",
    capabilityIds: ["gamepad-input", "input-remap", "keyboard-fallback"],
    keywords: ["手柄", "摇杆", "控制器", "按键映射"],
  },
  {
    id: "spatial-puzzle-3d",
    name: "立体空间谜题",
    description: "在有限 3D 场景中观察空间关系、操作机关并验证可达路径与相机可读性。",
    capabilityIds: ["character-controller", "camera", "3d-spatial-reasoning", "reachability", "checkpoint-save"],
    keywords: ["3d", "立体", "空间", "机关", "透视", "相机", "空间谜题"],
  },
];

export const getTemplate = (id: string | null): GameTemplate | undefined =>
  GAME_TEMPLATES.find((template) => template.id === id);
