import test from 'node:test';
import assert from 'node:assert/strict';
import {createState,edit,undo,step,segment,buildRoute,loop,scenicLoop,removeLast,decodeSave,START} from '../fixtures/meadow-railway/game-core.js';

test('railway: first simple action closes the starter route',()=>{const s=createState();assert.equal(edit(s,'left'), '');assert.equal(s.route.closed,true);assert.ok(s.route.length>60);assert.match(edit(s,'straight'),/闭环/);});
test('railway: all piece endpoints and tangents connect exactly',()=>{let p={...START};for(const type of['straight','left','up','bridge','right','tunnel','down']){const s=segment(p,type);assert.deepEqual(s.points[0],p);p=s.end;}assert.ok(Math.abs(p.y)<1e-8);});
test('railway: invalid underground, crossing and out of bounds edits preserve state',()=>{const s=createState([{type:'straight',color:0}]);const before=JSON.stringify(s.pieces);assert.match(edit(s,'down'),/地面/);assert.equal(JSON.stringify(s.pieces),before);for(let i=0;i<20;i++)edit(s,'straight');assert.ok(s.route.end.x<=54);assert.match(edit(s,'straight'),/边缘/);});
test('railway: undo redo restores exact routes and new edits clear redo',()=>{const s=createState();edit(s,'left');const closed=JSON.stringify(s.pieces);assert.ok(undo(s));assert.equal(s.route.closed,false);assert.ok(undo(s,true));assert.equal(JSON.stringify(s.pieces),closed);undo(s);edit(s,'straight');assert.equal(s.future.length,0);});
test('railway: closed train runs continuously, open train reverses and pause freezes',()=>{const s=createState(loop());s.running=true;for(let i=0;i<60*45;i++)step(s,1/60);assert.ok(s.trips>=2);assert.ok(s.distance<s.route.length);s.running=false;const before=s.time;step(s,1);assert.equal(s.time,before);const open=createState([{type:'straight',color:0}]);open.running=true;for(let i=0;i<60*8;i++)step(open,1/60);assert.ok(open.trips>=2);assert.ok(open.distance>=3.8&&open.distance<=6);});
test('railway: persistence round trip validates untrusted pieces and bounds',()=>{assert.deepEqual(decodeSave(JSON.stringify({version:1,pieces:loop()})),loop());for(const value of['bad','null',JSON.stringify({version:1,pieces:[{type:'down',color:0}]}),JSON.stringify({version:1,pieces:[{type:'script',color:0}]})])assert.equal(decodeSave(value),null);assert.equal(buildRoute(loop()).closed,true);});
test('railway: crossing a track at the same height is rejected without mutation',()=>{const s=createState([{type:'straight',color:0}]);for(let i=0;i<3;i++)assert.equal(edit(s,'left'),'');const before=JSON.stringify(s.pieces);assert.match(edit(s,'straight'),/撞上/);assert.equal(JSON.stringify(s.pieces),before);});
test('railway: scenic bridge/tunnel loop is legal piece by piece and survives save',()=>{const pieces=scenicLoop();assert.deepEqual(decodeSave(JSON.stringify({version:1,pieces})),pieces);const r=buildRoute(pieces);assert.equal(r.closed,true);assert.ok(r.points.some(p=>p.y>2.7));assert.equal(pieces.filter(p=>p.type==='tunnel').length,2);});
test('railway: closing a reversing train wraps negative distance and never stalls',()=>{const s=createState();s.direction=-1;s.distance=.01;s.running=true;assert.equal(edit(s,'left'),'');step(s,.1);assert.ok(s.distance>0&&s.distance<s.route.length);const before=s.distance;step(s,.1);assert.ok(s.distance<before);assert.equal(s.previous,before);});
test('railway: loaded closed layout can be opened directly and undo restores it',()=>{const s=createState(loop());s.distance=s.route.length-.01;s.previous=s.distance;s.direction=-1;assert.equal(s.history.length,0);assert.equal(removeLast(s),true);assert.equal(s.route.closed,false);assert.ok(s.distance<=s.route.length);assert.equal(s.previous,s.distance);assert.equal(undo(s),true);assert.equal(s.route.closed,true);assert.equal(undo(s,true),true);assert.ok(s.distance>=3.8&&s.distance<=s.route.length);});
