import type { GameDesignKnowledgeLibrary } from "./index.js";

const studioEvidence = (note: string) => ({
  sourceUrl: "https://github.com/mmlong818/ai-game-studio",
  observedAt: "2026-09-05",
  signal: "design-analysis" as const,
  note,
});

type Mechanic = GameDesignKnowledgeLibrary["mechanics"][number];
type Pattern = GameDesignKnowledgeLibrary["patterns"][number];

export const OFFICIAL_MECHANIC_EXTENSIONS: Mechanic[] = [
  { id: 'endpoint-track-assembly', label: '端点自动衔接构筑', family: 'spatial', playerVerb: '选择部件并沿现有端点方向接续', state: ['pieces', 'endpoint', 'heading', 'height'], inputs: ['append-piece', 'undo', 'redo'], outputs: ['piece-connected', 'intersection-rejected', 'loop-closed'], capabilityIds: ['unified-input', 'onboarding', 'local-persistence'], relations: [], tunableDimensions: ['space', 'operation'], probeSignals: ['piece-connected', 'loop-closed'] },
  { id: 'path-bound-vehicle', label: '沿构筑路径运行', family: 'movement', playerVerb: '启动或暂停沿自己搭建路线运行的车辆', state: ['path-distance', 'direction', 'running'], inputs: ['play', 'pause', 'return-station'], outputs: ['vehicle-moved', 'endpoint-reversed', 'circuit-completed'], capabilityIds: ['game-lifecycle', 'sensory-feedback'], relations: [{ targetId: 'endpoint-track-assembly', kind: 'complements', reason: '车辆沿构筑形成的同一条几何路径采样，显示与连接规则一致。' }], tunableDimensions: ['space'], probeSignals: ['vehicle-moved', 'endpoint-reversed'] },
  { id: 'continuous-kart-steering', label: '连续车辆转向', family: 'movement', playerVerb: '转动车头并改变赛道横向位置', state: ['track-distance', 'lateral-offset', 'heading', 'speed'], inputs: ['steer', 'brake'], outputs: ['heading-changed', 'lateral-position-changed', 'wall-contact'], capabilityIds: ['unified-input', 'onboarding', 'failure-assistance'], relations: [], tunableDimensions: ['operation', 'space', 'punishment'], probeSignals: ['heading-changed', 'lateral-position-changed'] },
  { id: 'circuit-lap-progress', label: '闭环赛道计圈', family: 'movement', playerVerb: '沿连续赛道顺向完成整圈', state: ['unwrapped-distance', 'lap', 'lap-time', 'finish-time'], inputs: ['drive'], outputs: ['lap-completed', 'race-finished'], capabilityIds: ['game-lifecycle', 'score-system', 'local-persistence'], relations: [{ targetId: 'continuous-kart-steering', kind: 'complements', reason: '计圈独立于转向手感，完整进度防止起点附近刷圈。' }], tunableDimensions: ['space'], probeSignals: ['three-laps-completed', 'race-result-visible'] },
  { id: 'energy-speed-burst', label: '消耗能量短时冲刺', family: 'risk-reward', playerVerb: '消耗积蓄的能量获得限时加速', state: ['energy', 'boost-timer', 'speed'], inputs: ['boost'], outputs: ['energy-consumed', 'speed-increased'], capabilityIds: ['sensory-feedback', 'score-system'], relations: [{ targetId: 'collect-charge', kind: 'complements', reason: '收集为可选加速提供资源，不能把不收集变成无法完赛。' }], tunableDimensions: ['resources', 'operation'], probeSignals: ['energy-consumed', 'speed-increased'] },
  { id: "gamepad-equivalent-control", label: "手柄等价控制", family: "movement", playerVerb: "用手柄完成与键盘和触控等价的核心动作", state: ["input-device", "focus", "mapping"], inputs: ["gamepad-axis", "gamepad-button"], outputs: ["player-action", "focus-feedback", "keyboard-fallback"], capabilityIds: ["unified-input", "accessible-presentation"], relations: [], tunableDimensions: ["operation"], probeSignals: ["gamepad-action-mapped", "keyboard-fallback-preserved"] },
  { id: "target-acquisition", label: "移动目标捕获", family: "timing", playerVerb: "发现并点击不断换位的目标", state: ["target-position", "time-remaining", "goal-progress"], inputs: ["point", "activate"], outputs: ["target-collected", "goal-completed"], capabilityIds: ["unified-input", "score-system", "difficulty-plan", "sensory-feedback"], relations: [], tunableDimensions: ["operation", "space", "punishment"], probeSignals: ["target-collected", "target-goal-completed"] },
  { id: "spatial-navigation", label: "三维移动探索", family: "movement", playerVerb: "移动角色穿越三维场景并接近目标", state: ["world-position", "velocity", "checkpoint", "goal"], inputs: ["move", "jump"], outputs: ["position-changed", "checkpoint-reached", "goal-reached"], capabilityIds: ["unified-input", "level-progression", "failure-assistance"], relations: [{ targetId: "collect-charge", kind: "complements", reason: "可选收集物为探索路线提供风险收益，但不阻断主线。" }], tunableDimensions: ["operation", "space", "punishment"], probeSignals: ["player-moved", "checkpoint-reached", "exit-reached"] },
  { id: "falling-blocks", label: "落块旋转消行", family: "spatial", playerVerb: "移动旋转下落拼块并消行", state: ["grid", "active-piece", "next-piece"], inputs: ["move", "rotate", "drop"], outputs: ["piece-locked", "line-cleared"], capabilityIds: ["score-system", "difficulty-plan", "sensory-feedback"], relations: [{ targetId: "polyomino-placement", kind: "complements", reason: "共享形状覆盖与空间规划知识，但时间压力不同。" }], tunableDimensions: ["operation", "space", "cognition"], probeSignals: ["piece-rotated", "line-cleared"] },
  { id: "drag-snap-assembly", label: "拖拽吸附拼合", family: "spatial", playerVerb: "拖动部件到正确位置并吸附", state: ["piece", "target-slot", "placed"], inputs: ["drag", "drop"], outputs: ["piece-snapped", "assembly-progress"], capabilityIds: ["unified-input", "onboarding", "accessible-presentation"], relations: [], tunableDimensions: ["cognition", "operation", "space"], probeSignals: ["piece-dragged", "piece-snapped"] },
  { id: "paddle-trajectory", label: "挡板反弹轨迹", family: "timing", playerVerb: "移动挡板改变反弹角度并保持弹球", state: ["ball", "paddle", "targets", "lives"], inputs: ["move-paddle"], outputs: ["ball-reflected", "target-hit", "life-lost"], capabilityIds: ["unified-input", "score-system", "sensory-feedback"], relations: [], tunableDimensions: ["operation", "space", "punishment"], probeSignals: ["paddle-moved", "brick-hit"] },
  { id: "grid-navigation", label: "网格路径探索", family: "movement", playerVerb: "在有边界的地图中探索并抵达目标", state: ["grid", "position", "visited", "goal"], inputs: ["move-direction"], outputs: ["position-changed", "goal-reached"], capabilityIds: ["unified-input", "level-progression", "failure-assistance"], relations: [{ targetId: "constraint-deduction", kind: "complements", reason: "路径可叠加钥匙、开关或信息约束。" }], tunableDimensions: ["cognition", "space", "resources"], probeSignals: ["cell-entered", "exit-reached"] },
  { id: "sliding-block", label: "占格移块脱困", family: "spatial", playerVerb: "在不可重叠约束下腾挪方块", state: ["grid", "blocks", "exit"], inputs: ["slide-block"], outputs: ["legal-move", "target-exited"], capabilityIds: ["onboarding", "failure-assistance", "level-progression"], relations: [{ targetId: "constraint-deduction", kind: "complements", reason: "合法移动和可解性可由约束求解共同验证。" }], tunableDimensions: ["cognition", "space", "punishment"], probeSignals: ["block-moved", "puzzle-solved"] },
  { id: "trail-growth", label: "持续移动轨迹增长", family: "movement", playerVerb: "转向收集并避免撞上边界或自身轨迹", state: ["head", "trail", "pickup"], inputs: ["turn"], outputs: ["pickup-collected", "trail-grown", "collision"], capabilityIds: ["unified-input", "score-system", "difficulty-plan"], relations: [{ targetId: "collect-charge", kind: "substitutes", reason: "收集物用于增长时不应同时默认承担蓄能。" }], tunableDimensions: ["operation", "space", "punishment"], probeSignals: ["direction-changed", "trail-grown"] },
  { id: "projectile-wave", label: "弹体射击与波次", family: "combat", playerVerb: "走位、射击并清除敌人波次", state: ["player", "projectiles", "enemies", "wave"], inputs: ["move", "fire"], outputs: ["projectile-fired", "enemy-hit", "wave-cleared"], capabilityIds: ["unified-input", "score-system", "difficulty-plan", "sensory-feedback"], relations: [{ targetId: "resource-upgrade", kind: "enables", reason: "升级可形成武器或生存构筑。" }], tunableDimensions: ["operation", "space", "combination", "punishment"], probeSignals: ["shot-fired", "enemy-hit", "wave-cleared"] },
  { id: "polyomino-placement", label: "多格拼块放置", family: "spatial", playerVerb: "选择旋转并放置多格形状", state: ["grid", "pieces", "coverage"], inputs: ["select-piece", "rotate", "place"], outputs: ["piece-placed", "coverage-changed", "line-cleared"], capabilityIds: ["score-system", "difficulty-plan", "failure-assistance"], relations: [{ targetId: "falling-blocks", kind: "complements", reason: "共享形状规则，可采用无时间压力的放置变体。" }], tunableDimensions: ["cognition", "space", "resources"], probeSignals: ["piece-placed", "coverage-completed"] },
  { id: "constraint-deduction", label: "约束排除推理", family: "information", playerVerb: "读取线索、排除候选并验证答案", state: ["constraints", "candidates", "marks"], inputs: ["mark", "commit"], outputs: ["candidate-eliminated", "solution-validated"], capabilityIds: ["failure-assistance", "level-progression", "accessible-presentation"], relations: [{ targetId: "grid-navigation", kind: "complements", reason: "线索可控制路径开放，但必须保持可解释。" }], tunableDimensions: ["cognition", "resources", "punishment"], probeSignals: ["candidate-eliminated", "solution-validated"] },
  { id: "route-relic-synergy", label: "路线选择与遗物协同", family: "risk-reward", playerVerb: "在风险、奖励和构筑方向之间选择路线", state: ["route", "relics", "encounter", "run"], inputs: ["choose-route", "choose-relic"], outputs: ["encounter-entered", "synergy-changed"], capabilityIds: ["level-progression", "local-persistence", "failure-assistance"], relations: [{ targetId: "deck-synergy", kind: "substitutes", reason: "遗物可承担构筑层，不要求同时存在牌组。" }], tunableDimensions: ["cognition", "resources", "combination", "punishment"], probeSignals: ["route-chosen", "relic-triggered"] },
  { id: "tableau-solitaire", label: "牌列腾挪与收牌", family: "spatial", playerVerb: "在牌列和空档间合法移动序列并完成收牌", state: ["tableau", "free-cells", "foundations"], inputs: ["move-card", "auto-foundation", "undo"], outputs: ["card-moved", "foundation-built", "deal-solved"], capabilityIds: ["failure-assistance", "local-persistence", "onboarding"], relations: [{ targetId: "deck-synergy", kind: "conflicts", reason: "接龙是确定性空间规划，不应误配为随机牌组构筑。" }], tunableDimensions: ["cognition", "space", "resources"], probeSignals: ["legal-move-applied", "foundation-completed"] },
  { id: "spatial-rotation-path", label: "三维转动连接路径", family: "spatial", playerVerb: "转动场景改变连接关系并移动到出口", state: ["orientation", "links", "position", "goal"], inputs: ["rotate-world", "move", "jump"], outputs: ["orientation-changed", "link-enabled", "goal-reached"], capabilityIds: ["unified-input", "level-progression", "failure-assistance"], relations: [{ targetId: "grid-navigation", kind: "requires", reason: "转动改变的是底层路径图的连接状态。" }], tunableDimensions: ["cognition", "space", "combination"], probeSignals: ["world-rotated", "angle-link-used", "exit-reached"] },
];

const baseCapabilities = ["game-lifecycle", "onboarding", "difficulty-plan", "failure-assistance"];
const pattern = (value: Omit<Pattern, "evidence" | "evaluationVersion"> & { evidenceNote: string }): Pattern => {
  const { evidenceNote, ...rest } = value;
  return { ...rest, evidence: [studioEvidence(evidenceNote)], evaluationVersion: 1 };
};

export const OFFICIAL_PATTERN_EXTENSIONS: Pattern[] = [
  pattern({ id: 'toy-railway-sandbox', label: '轨道玩具沙盒', summary: '逐段搭建连续轨道，观察列车沿自己的路线旅行，自由撤销和改造。', scope: { dimensions: ['limited-3d'], sessionMinutes: [2, 30], inputs: ['pointer', 'touch', 'keyboard'] }, tags: ['sandbox', 'construction', 'limited-3d'], coreCapabilityIds: baseCapabilities, coreMechanicIds: ['endpoint-track-assembly', 'path-bound-vehicle'], optionalMechanicIds: [], compositionRules: ['轨道生成与车辆采样使用同一条路径。', '开放线路可折返，不把闭环强制作为开玩门槛。'], knownRisks: ['相交轨道与高架净空必须明确检查。', '大量几何应合批并验证重建释放。'], lifecycle: 'candidate', evidenceNote: '2026-09-06 实际浏览 Choo-Choo World 的搭建引导与工具，牧野小火车独立原型尚待真人品质审核。' }),
  pattern({ id: 'assisted-circuit-racing', label: '轻操作闭环竞速', summary: '自动前进与可选转向辅助降低入门门槛，路线、超车与冲刺时机构成比赛。', scope: { dimensions: ['limited-3d'], sessionMinutes: [2, 5], inputs: ['keyboard', 'touch'] }, tags: ['racing', 'arcade', 'limited-3d'], coreCapabilityIds: baseCapabilities, coreMechanicIds: ['continuous-kart-steering', 'circuit-lap-progress'], optionalMechanicIds: ['energy-speed-burst', 'collect-charge'], compositionRules: ['玩家与对手共用车辆规则；不能依靠瞬移追赶。', '比赛不中断升级，圈数和自由驾驶结束条件分离。'], knownRisks: ['转向辅助过强会削弱参与感；过弱会增加触屏负担。', '镜头、遮挡和 3D 渲染预算必须通过实机验证。'], lifecycle: 'candidate', evidenceNote: '2026-09-06 用户提供海岛卡丁车视频；原创实现与本地规则测试，不代表已通过用户品质审核。' }),
  pattern({ id: "timed-target-hunt", label: "限时目标捕获", summary: "观察不断换位的高对比目标，在短时限内连续定位并点击完成数量目标。", scope: { dimensions: ["2d"], sessionMinutes: [.5, 3], inputs: ["pointer", "touch", "keyboard"] }, tags: ["reaction", "search", "score", "casual"], coreCapabilityIds: baseCapabilities, coreMechanicIds: ["target-acquisition"], optionalMechanicIds: [], compositionRules: ["首次捕获暂停倒计时，目标始终避开遮挡区并保持可聚焦。"], knownRisks: ["随机换位可能落入小屏遮挡区或只考验机械点击速度。"], lifecycle: "verified", evidenceNote: "雾港信号模板通过二十关、持久化和真实浏览器点击验收。" }),
  pattern({ id: "third-person-collection", label: "第三人称收集探索", summary: "在有限三维场景中移动、跳跃、激活检查点并选择是否探索额外收集物。", scope: { dimensions: ["limited-3d"], sessionMinutes: [2, 15], inputs: ["keyboard", "touch", "gamepad"] }, tags: ["exploration", "collection", "checkpoint", "limited-3d"], coreCapabilityIds: baseCapabilities, coreMechanicIds: ["spatial-navigation"], optionalMechanicIds: ["collect-charge"], compositionRules: ["主线检查点与出口始终可达，可选收集物只影响评价。"], knownRisks: ["镜头、碰撞高度和跳跃落点可能在手机上难以判断。"], lifecycle: "verified", evidenceNote: "潮汐遗迹收集模板通过20关、检查点、恢复、碰撞与真实浏览器验收。" }),
  pattern({ id: "turn-match3-duel", label: "回合对抗三消", summary: "共享棋盘的匹配结果转化为双方资源和回合优势。", scope: { dimensions: ["2d"], sessionMinutes: [5, 15], inputs: ["pointer", "touch"] }, tags: ["match", "turn-based", "strategy"], coreCapabilityIds: baseCapabilities, coreMechanicIds: ["match-combo"], optionalMechanicIds: ["resource-upgrade"], compositionRules: ["交换、连消、技能和对手响应的顺序必须确定。"], knownRisks: ["对手决策和特殊棋子组合易造成不可解释结果。"], lifecycle: "verified", evidenceNote: "星梦对决官方黄金游戏与确定性探针。" }),
  pattern({ id: "falling-block-puzzle", label: "落块消行", summary: "在持续下落压力下旋转移动拼块并完成横行。", scope: { dimensions: ["2d"], sessionMinutes: [2, 10], inputs: ["keyboard", "touch", "gamepad"] }, tags: ["puzzle", "action", "score"], coreCapabilityIds: baseCapabilities, coreMechanicIds: ["falling-blocks"], optionalMechanicIds: [], compositionRules: ["先教学移动旋转，再逐档提高落速和空间压力。"], knownRisks: ["手机软降、硬降和旋转区域容易误触。"], lifecycle: "verified", evidenceNote: "落块官方模板通过二十关与浏览器验收。" }),
  pattern({ id: "drag-assembly-puzzle", label: "拖拽拼合", summary: "观察目标轮廓，拖动或旋转部件完成空间拼合。", scope: { dimensions: ["2d"], sessionMinutes: [2, 15], inputs: ["pointer", "touch"] }, tags: ["puzzle", "spatial", "casual"], coreCapabilityIds: baseCapabilities, coreMechanicIds: ["drag-snap-assembly"], optionalMechanicIds: ["polyomino-placement"], compositionRules: ["吸附容差和参考提示随阶段逐步收紧。"], knownRisks: ["触控遮挡和小部件命中区域影响可用性。"], lifecycle: "verified", evidenceNote: "图片拼图与多格拼合官方模板。" }),
  pattern({ id: "ricochet-breakout", label: "反弹清场", summary: "移动挡板保持弹球并利用角度连续击破目标。", scope: { dimensions: ["2d"], sessionMinutes: [2, 8], inputs: ["keyboard", "pointer", "touch"] }, tags: ["arcade", "action", "score"], coreCapabilityIds: baseCapabilities, coreMechanicIds: ["paddle-trajectory"], optionalMechanicIds: [], compositionRules: ["反弹角度可预测，失败后快速重开。"], knownRisks: ["最后少量目标可能造成无意义等待。"], lifecycle: "verified", evidenceNote: "打砖块官方模板与动作探针。" }),
  pattern({ id: "sliding-block-escape", label: "移块脱困", summary: "在固定占格和不可重叠约束中为目标块腾出出口。", scope: { dimensions: ["2d"], sessionMinutes: [2, 15], inputs: ["pointer", "touch"] }, tags: ["puzzle", "spatial", "solver"], coreCapabilityIds: baseCapabilities, coreMechanicIds: ["sliding-block"], optionalMechanicIds: [], compositionRules: ["每关必须有求解证明，提示基于真实解路径。"], knownRisks: ["只扩大棋盘会增加繁琐而非有效难度。"], lifecycle: "verified", evidenceNote: "华容道官方模板和合法移动/求解器。" }),
  pattern({ id: "maze-navigation", label: "迷宫路径探索", summary: "在有限信息或机关约束下建立路线并抵达出口。", scope: { dimensions: ["2d", "limited-3d"], sessionMinutes: [2, 15], inputs: ["keyboard", "touch", "gamepad"] }, tags: ["maze", "exploration", "puzzle"], coreCapabilityIds: baseCapabilities, coreMechanicIds: ["grid-navigation"], optionalMechanicIds: ["constraint-deduction"], compositionRules: ["入口到出口始终可达，迷雾不隐藏必要规则。"], knownRisks: ["大地图可能只增加记忆负担。"], lifecycle: "verified", evidenceNote: "迷宫官方模板与可达性验收。" }),
  pattern({ id: "trail-survival", label: "轨迹增长生存", summary: "持续移动、收集增长并管理自身轨迹压缩的空间。", scope: { dimensions: ["2d"], sessionMinutes: [2, 8], inputs: ["keyboard", "touch", "gamepad"] }, tags: ["action", "survival", "score"], coreCapabilityIds: baseCapabilities, coreMechanicIds: ["trail-growth"], optionalMechanicIds: [], compositionRules: ["禁止直接反向，首个收集物位于安全路径。"], knownRisks: ["速度和身体长度同时上涨会造成突刺。"], lifecycle: "verified", evidenceNote: "贪吃蛇官方模板与持续移动验收。" }),
  pattern({ id: "wave-shooter", label: "波次射击", summary: "移动射击、规避威胁并完成逐步组合的敌人波次。", scope: { dimensions: ["2d", "limited-3d"], sessionMinutes: [3, 15], inputs: ["keyboard", "touch", "gamepad"] }, tags: ["action", "shooter", "waves"], coreCapabilityIds: baseCapabilities, coreMechanicIds: ["projectile-wave"], optionalMechanicIds: ["resource-upgrade"], compositionRules: ["敌人行为先单独教学，再组合进同一波次。"], knownRisks: ["弹体、敌人和特效数量可能超过性能预算。"], lifecycle: "verified", evidenceNote: "太空射击官方模板与3D竞技场补充模板。" }),
  pattern({ id: "polyomino-space-planning", label: "拼块空间规划", summary: "在有限候选中选择拼块，管理覆盖和后续可放空间。", scope: { dimensions: ["2d"], sessionMinutes: [2, 10], inputs: ["pointer", "touch"] }, tags: ["puzzle", "spatial", "score"], coreCapabilityIds: baseCapabilities, coreMechanicIds: ["polyomino-placement"], optionalMechanicIds: [], compositionRules: ["每次候选至少保留合法放置，失败条件可预见。"], knownRisks: ["随机候选可能制造无解而非公平挑战。"], lifecycle: "verified", evidenceNote: "多格拼合与方块填阵官方模板。" }),
  pattern({ id: "constraint-logic", label: "约束逻辑推理", summary: "读取明确线索、逐步排除并验证唯一或允许的解。", scope: { dimensions: ["2d"], sessionMinutes: [3, 20], inputs: ["pointer", "touch", "keyboard"] }, tags: ["puzzle", "logic", "deduction"], coreCapabilityIds: baseCapabilities, coreMechanicIds: ["constraint-deduction"], optionalMechanicIds: [], compositionRules: ["所有结论必须能追溯到已展示约束。"], knownRisks: ["自动提示若只报答案会破坏学习。"], lifecycle: "verified", evidenceNote: "区域逻辑官方模板、唯一解和提示解释器。" }),
  pattern({ id: "tile-route-roguelite", label: "牌块路线构筑", summary: "完成局部消除或挑战后选择路线与遗物形成一局构筑。", scope: { dimensions: ["2d"], sessionMinutes: [5, 25], inputs: ["pointer", "touch"] }, tags: ["roguelite", "route", "build"], coreCapabilityIds: baseCapabilities, coreMechanicIds: ["route-relic-synergy"], optionalMechanicIds: ["deck-synergy"], compositionRules: ["路线风险、奖励和遗物触发顺序必须可预览。"], knownRisks: ["随机布局与遗物组合会扩大验证空间。"], lifecycle: "verified", evidenceNote: "麻将肉鸽官方模板与种子路线验收。" }),
  pattern({ id: "freecell-solitaire", label: "空档接龙", summary: "利用有限空档搬运牌列并按花色完成收牌。", scope: { dimensions: ["2d"], sessionMinutes: [5, 30], inputs: ["pointer", "touch"] }, tags: ["card", "puzzle", "solver"], coreCapabilityIds: baseCapabilities, coreMechanicIds: ["tableau-solitaire"], optionalMechanicIds: [], compositionRules: ["每次移动合法，超级移动上限可解释且牌局有求解证据。"], knownRisks: ["自动收牌不能拿走玩家仍需使用的牌。"], lifecycle: "verified", evidenceNote: "空档接龙官方游戏、微软牌局复现与100局求解测试。" }),
  pattern({ id: "popup-spatial-puzzle", label: "转景连路3D谜题", summary: "转动立体场景改变道路连接，再移动收集并抵达出口。", scope: { dimensions: ["limited-3d"], sessionMinutes: [3, 15], inputs: ["keyboard", "touch", "gamepad"] }, tags: ["puzzle", "spatial", "limited-3d"], coreCapabilityIds: baseCapabilities, coreMechanicIds: ["grid-navigation", "spatial-rotation-path"], optionalMechanicIds: [], compositionRules: ["角度变化、连接出现和可达性必须由同一图规则验证。"], knownRisks: ["镜头、跳跃和障碍可读性仍需真实玩家验证。"], lifecycle: "candidate", evidenceNote: "纸境立体书仍处 development，已有20关求解与浏览器探针但尚未上线。" }),
];
