import { useComponentLocale } from "./component-i18n";

const zhCN = { label: "游戏方案", formed: "方案已形成", remixTitle: "{title}改造方案", newTitle: "新游戏机制方案", referenceDetail: "先确认基础复刻是否准确。系统会保留参考中已经核实的关卡和局制，不会擅自改玩法；不合适就返回修改。", newDetail: "先看看这一局玩家会怎样玩。符合你的想法就继续制作单局 demo，不合适就返回修改；不会默认增加关卡、等级或教学系统。", stamp: "方案草案 · 待制作验证", summary: "方案摘要", based: "基于的玩法", scope: "改动范围", loop: "玩家会反复做什么", requirements: "你的要求", yourWords: "你写的话", direction: "我们理解的玩法方向", how: "具体怎么玩", action: "玩家要做什么", actionFallback: "先明确玩家最常做的一个动作，再确定其他规则。", example: "实际玩一小段", goal: "怎样过关或结束", combination: "上面列出的是不同玩法方向的候选规则，不是要求玩家同时完成所有目标；它们怎样配合、以哪个目标为准，制作前仍需确认。", preserve: "本次改造需要照顾的体验", experience: "建议做成怎样的完整体验", checks: "制作时需要完成的检查", pending: "待验证", core: "核心玩法与胜负规则", feedback: "操作反馈是否清楚", reference: "参考中的关卡与局制", rhythm: "单局节奏", art: "图像资源与胜利结算", devices: "桌面、触控与运行流畅度", sources: "已收录的参考资料：{count} 项", quota: "点击“继续”后将保存方案、分析并制作游戏；模型分析和图片生成可能使用已配置的模型额度。", back: "返回修改", continue: "继续" } as const;
type Key = keyof typeof zhCN;
const tables: Record<string, Record<Key, string>> = {
  "zh-CN": zhCN,
  "zh-TW": { label: "遊戲方案", formed: "方案已形成", remixTitle: "{title}改造方案", newTitle: "新遊戲機制方案", referenceDetail: "先確認基礎復刻是否準確。系統會保留參考中已核實的關卡和局制，不會擅自改玩法；不合適就返回修改。", newDetail: "先看看這一局玩家會怎樣玩。符合想法就繼續製作單局 demo，不合適就返回修改；不會預設增加關卡、等級或教學系統。", stamp: "方案草案 · 待製作驗證", summary: "方案摘要", based: "基於的玩法", scope: "改動範圍", loop: "玩家會反覆做什麼", requirements: "你的要求", yourWords: "你寫的話", direction: "我們理解的玩法方向", how: "具體怎麼玩", action: "玩家要做什麼", actionFallback: "先明確玩家最常做的一個動作，再確定其他規則。", example: "實際玩一小段", goal: "怎樣過關或結束", combination: "上面列出的是不同玩法方向的候選規則，不要求同時完成所有目標；它們如何配合、以哪個目標為準，製作前仍需確認。", preserve: "本次改造需要照顧的體驗", experience: "建議做成怎樣的完整體驗", checks: "製作時需要完成的檢查", pending: "待驗證", core: "核心玩法與勝負規則", feedback: "操作回饋是否清楚", reference: "參考中的關卡與局制", rhythm: "單局節奏", art: "圖像資源與勝利結算", devices: "桌面、觸控與執行流暢度", sources: "已收錄的參考資料：{count} 項", quota: "點擊「繼續」後將保存方案、分析並製作遊戲；模型分析和圖片生成可能使用已設定的模型額度。", back: "返回修改", continue: "繼續" },
  en: { label: "Game plan", formed: "Plan ready", remixTitle: "Remix plan for {title}", newTitle: "New game mechanic plan", referenceDetail: "Confirm that the basic recreation is accurate first. Verified levels and modes from the reference are preserved; gameplay is not changed without your direction. Go back if it is not right.", newDetail: "See how one round plays. Continue to build a single-round demo if it matches your idea, or go back to revise it. Levels, ranks, and tutorials are not added by default.", stamp: "Draft plan · Production validation pending", summary: "Plan summary", based: "Based on", scope: "Change scope", loop: "What players repeat", requirements: "Your requirements", yourWords: "Your words", direction: "Our gameplay interpretation", how: "How it plays", action: "Player action", actionFallback: "Define the player's most frequent action before deciding the other rules.", example: "A short play example", goal: "How the round ends", combination: "These are candidate rules from different gameplay directions, not simultaneous objectives. Their relationship and primary objective still need confirmation before production.", preserve: "Experience to preserve in this remix", experience: "Recommended complete experience", checks: "Checks required during production", pending: "Pending", core: "Core gameplay and outcome rules", feedback: "Clarity of control feedback", reference: "Referenced levels and modes", rhythm: "Single-round pacing", art: "Image assets and victory presentation", devices: "Desktop, touch, and runtime performance", sources: "Reference sources included: {count}", quota: "Continue saves and analyzes the plan, then builds the game. Model analysis and image generation may use configured quota.", back: "Back to edit", continue: "Continue" },
  ja: { label: "ゲーム企画", formed: "企画ができました", remixTitle: "{title} の改造案", newTitle: "新ゲームの仕組み案", referenceDetail: "まず基本の再現が正しいか確認してください。参照元で確認済みのステージやモードは保持し、勝手に遊び方を変えません。合わなければ戻って修正できます。", newDetail: "1回の流れを確認してください。イメージに合えば単一ラウンドの demo を制作し、合わなければ戻って修正できます。ステージ、ランク、チュートリアルは自動追加しません。", stamp: "企画案 · 制作検証待ち", summary: "企画概要", based: "元の遊び方", scope: "変更範囲", loop: "繰り返す行動", requirements: "あなたの要望", yourWords: "入力した内容", direction: "理解した遊び方", how: "具体的な遊び方", action: "プレイヤーの行動", actionFallback: "最も頻繁に行う動作を決めてから、ほかのルールを定めます。", example: "短いプレイ例", goal: "クリアまたは終了条件", combination: "上記は異なる方向の候補ルールで、すべてを同時達成する意味ではありません。組み合わせと主目標は制作前に確認が必要です。", preserve: "今回の改造で大切にする体験", experience: "おすすめの完全な体験", checks: "制作中に必要な検査", pending: "検証待ち", core: "基本の遊び方と勝敗ルール", feedback: "操作フィードバックの明瞭さ", reference: "参照元のステージとモード", rhythm: "1ラウンドのテンポ", art: "画像素材と勝利演出", devices: "デスクトップ、タッチ、動作の滑らかさ", sources: "収録した参照資料：{count}件", quota: "「続ける」を押すと企画を保存・分析してゲームを制作します。モデル分析と画像生成で設定済みの利用枠を使う場合があります。", back: "修正に戻る", continue: "続ける" },
};
export function useReviewMessages() { const locale = useComponentLocale(); return (key: Key, values: Record<string, string | number> = {}) => Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), tables[locale][key]); }
