import { puzzleWorkshopScript } from './puzzle-workshop.js';

export const puzzleScript = puzzleWorkshopScript + String.raw`
const puzzleBlueprints = [
  ["晨叶初光","认识轮廓",6,.3,3,false,0],["风铃花窗","认识轮廓",9,.28,3,false,0],
  ["软云茶会","认识轮廓",12,.26,3,false,0],["珊瑚邮局","认识轮廓",16,.24,3,false,0],
  ["橘猫温室","组织外围",20,.22,2,false,0],["月兔电台","组织外围",24,.2,2,false,0],
  ["果冻列车","组织外围",20,.2,2,false,0],["星砂书店","组织外围",24,.18,2,false,0],
  ["雨后街角","纹理判断",30,.16,2,false,0],["莓果天台","纹理判断",30,.15,2,false,0],
  ["浮岛花园","纹理判断",36,.14,2,false,0],["海盐灯塔","纹理判断",36,.13,2,false,0],
  ["夜航市集","组合压力",42,.12,1,true,0],["玻璃森林","组合压力",42,.11,1,true,0],
  ["鲸歌车站","组合压力",48,.1,1,true,0],["糖霜剧场","组合压力",48,.09,1,true,0],
  ["彗星花房","最终掌握",50,.08,1,true,0],["银杏博物馆","最终掌握",50,.07,1,true,0],
  ["蓝调水族馆","最终掌握",50,.06,1,true,210],["植光终章","最终掌握",50,.05,1,true,180],
].map((value,index)=>({number:index+1,name:value[0],chapter:value[1],pieceCount:value[2],guideOpacity:value[3],hintUses:value[4],rotationRecommended:value[5],challengeSeconds:value[6]}));

let image = new Image();
let pieces = [];
let columns = 4;
let rows = 3;
let board = { x:110,y:260,width:500,height:750,cellWidth:100,cellHeight:75 };
let activePieceCount = config.puzzleRules ? config.puzzleRules.pieceCount : 20;
let activeLevelId = config.imageLevels?.[0]?.id || "pocket-garden";
let puzzleImageLoading = true;
let puzzleImageRequestId = 0;
let selectedGroupId = null;
let dragState = null;
let panState = null;
let groupSequence = 0;
let placedCount = 0;
let moves = 0;
let bounceCount = 0;
let connectionCount = 0;
let hintsRemaining = 3;
let hintsUsed = 0;
let hintPieceIndex = -1;
let hintUntil = 0;
let previewUntil = 0;
let previewStartedAt = 0;
let connectionPulseUntil = 0;
let completionUntil = 0;
let completionToken = 0;
let trayScale = .72;
let edgeOnly = false;
let rotationEnabled = false;
let puzzleMode = "classic";
let puzzlePaused = false;
let viewScale = 1;
let viewPan = { x:0,y:0 };
let timeLimitMs = 0;
let remainingMs = 0;
let startedAt = 0;
let lastFrameAt = 0;
let lastTimerSecond = -1;
let restoredPieces = 0;
let validation = null;
let pendingPuzzleRestart = false;
let regionFilter = 'all';
let restoredGroups = 0;
let elapsedActiveMs = 0;
let workshopHintIndex = -1;
function puzzleWorkAreaBottom(){return canvas.height-(window.matchMedia('(max-width:720px)').matches?170:140)*canvas.height/Math.max(1,canvas.getBoundingClientRect().height);}

const workshopStyle = document.createElement('style');
workshopStyle.textContent = '.puzzle-workshop-filter{font:inherit;color:inherit;background:var(--theme-panel);border:1px solid var(--theme-line);border-radius:8px;min-height:40px;max-width:100%;width:100%;padding:0 4px}.puzzle-tools .puzzle-workshop-filter:focus-visible{outline:3px solid #4f9f91;outline-offset:2px}';
workshopStyle.textContent += 'body[data-template=puzzle] .onboarding-coach:not(.is-compact){top:auto;bottom:18px;right:10px;width:min(360px,calc(100% - 20px));padding:8px;gap:4px;box-sizing:border-box;z-index:8}body[data-template=puzzle] .onboarding-coach:not(.is-compact) small{display:none}body[data-template=puzzle] .onboarding-coach .onboarding-actions{margin-top:0}body[data-template=puzzle] .onboarding-coach.is-compact{top:auto;bottom:18px}body[data-template=puzzle] [data-control=rotate]:disabled{display:none}body[data-template=puzzle]:not([data-game-state=playing]) .puzzle-workshop-filter{display:none}@media(max-width:720px){body[data-template=puzzle] .onboarding-coach:not(.is-compact){bottom:104px;width:calc(100% - 20px)}body[data-template=puzzle] .onboarding-coach.is-compact{bottom:104px}}';
document.head.appendChild(workshopStyle);
document.querySelectorAll('.puzzle-tools').forEach((toolbar)=>{const select=document.createElement('select');select.className='puzzle-workshop-filter';select.setAttribute('aria-label','按画面区域整理拼块');select.dataset.puzzleRegion='';[['all','全部区域'],['0','画面上部'],['1','画面中部'],['2','画面下部']].forEach(([value,label])=>select.add(new Option(label,value)));select.addEventListener('change',()=>{if(!running||puzzlePaused)return;regionFilter=select.value;edgeOnly=false;selectedGroupId=null;syncPuzzleControls();persistPuzzleSession();setStatus('只筛选可见拼块，不移动、不拆组；随时选全部区域。');drawPuzzle();});toolbar.appendChild(select);});

function visibleWorkshopPiece(piece){return puzzleWorkshopVisible(piece,pieces,edgeOnly?'edge':regionFilter,rows);}
function drawWorkshopGuide(){const progress=puzzleWorkshopProgress(pieces,rows,columns);ctx.save();ctx.fillStyle='#426a5b';ctx.textAlign='center';ctx.font='700 18px Microsoft YaHei,sans-serif';ctx.fillText('四角 '+progress.corners.done+'/'+progress.corners.total+'   ·   边框 '+progress.frame.done+'/'+progress.frame.total+'   ·   区域 '+progress.regions.filter((r)=>r.total&&r.done===r.total).length+'/'+progress.regions.filter((r)=>r.total).length,canvas.width/2,28);ctx.font='500 14px Microsoft YaHei,sans-serif';ctx.fillStyle='#766961';ctx.fillText(puzzleWorkshopLesson(currentCampaignLevel().number,progress,connectionCount),canvas.width/2,51);ctx.restore();}

const pieceCountInputs = Array.from(document.querySelectorAll("[data-puzzle-count]"));
const levelInputs = Array.from(document.querySelectorAll("[data-puzzle-level]"));
const modeButtons = Array.from(document.querySelectorAll("[data-puzzle-mode]"));
const rotationInput = document.querySelector("[data-puzzle-rotation]");
const puzzleBlueprint = () => puzzleBlueprints[Math.max(0,Math.min(19,currentCampaignLevel().number-1))];

function syncInputs(inputs,value){inputs.forEach((input)=>{input.value=String(value);});}
function activeLevelLabel(){return config.imageLevels?.find((level)=>level.id===activeLevelId)?.label||"我的图片";}
function puzzleSessionKey(){return config.campaignStorageKey+"-puzzle-session-v2";}
function setPuzzleImageLoading(loading){puzzleImageLoading=loading;startButton.disabled=loading;startButton.setAttribute("aria-busy",String(loading));if(loading)setStatus("正在载入关卡图片，请稍候。");}
function beginPuzzleImageLoad(){puzzleImageRequestId+=1;setPuzzleImageLoading(true);return puzzleImageRequestId;}
function clearPuzzleCanvas(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#eee9e2";ctx.fillRect(0,0,canvas.width,canvas.height);const light=ctx.createRadialGradient(canvas.width*.5,canvas.height*.48,30,canvas.width*.5,canvas.height*.48,canvas.height*.62);light.addColorStop(0,"rgba(255,255,255,.88)");light.addColorStop(.68,"rgba(250,246,240,.64)");light.addColorStop(1,"rgba(212,202,194,.42)");ctx.fillStyle=light;ctx.fillRect(0,0,canvas.width,canvas.height);}

function gridForImage(){
  const aspect=Math.max(.25,Math.min(4,image.naturalWidth/image.naturalHeight));const candidates=[];
  for(let candidateRows=2;candidateRows<=activePieceCount;candidateRows+=1){if(activePieceCount%candidateRows!==0)continue;const candidateColumns=activePieceCount/candidateRows;if(candidateColumns<2)continue;candidates.push({rows:candidateRows,columns:candidateColumns});}
  const best=candidates.sort((left,right)=>Math.abs(Math.log((left.columns/left.rows)/aspect))-Math.abs(Math.log((right.columns/right.rows)/aspect)))[0]||{rows:4,columns:5};columns=best.columns;rows=best.rows;
}
function layoutBoard(){
  const aspect=Math.max(.25,Math.min(4,image.naturalWidth/image.naturalHeight));const maxWidth=config.aspectRatio==="9:16"?510:560;const maxHeight=Math.max(240,Math.min(config.aspectRatio==="9:16"?760:610,puzzleWorkAreaBottom()-290));let width=maxWidth,height=width/aspect;if(height>maxHeight){height=maxHeight;width=height*aspect;}
  board={x:(canvas.width-width)/2,y:70+(puzzleWorkAreaBottom()-70-height)/2,width,height,cellWidth:width/columns,cellHeight:height/rows};const horizontalCount=Math.max(2,Math.ceil(activePieceCount*.3));const verticalCount=Math.max(1,Math.ceil((activePieceCount-horizontalCount*2)/2));const sideScale=Math.min((board.x-10)*2/board.cellWidth,(canvas.width-board.x-board.width-10)*2/board.cellWidth);trayScale=Math.max(.42,Math.min(.88,sideScale,(canvas.width-26)/(horizontalCount*board.cellWidth*1.04),board.height/(verticalCount*board.cellHeight*1.05)));
}
function boundarySign(kind,row,column){const seed=row*31+column*17+currentCampaignLevel().seed+(kind==="horizontal"?7:13);return seed%2===0?1:-1;}
function edgesFor(row,column){return{top:row===0?0:-boundarySign("horizontal",row-1,column),right:column===columns-1?0:boundarySign("vertical",row,column),bottom:row===rows-1?0:boundarySign("horizontal",row,column),left:column===0?0:-boundarySign("vertical",row,column-1)};}
function horizontalEdge(path,startX,y,deltaX,sign,outward){if(!sign){path.lineTo(startX+deltaX,y);return;}const depth=Math.min(Math.abs(deltaX),board.cellHeight)*.21*sign*outward;path.lineTo(startX+deltaX*.34,y);path.bezierCurveTo(startX+deltaX*.34,y+depth,startX+deltaX*.66,y+depth,startX+deltaX*.66,y);path.lineTo(startX+deltaX,y);}
function verticalEdge(path,x,startY,deltaY,sign,outward){if(!sign){path.lineTo(x,startY+deltaY);return;}const depth=Math.min(Math.abs(deltaY),board.cellWidth)*.21*sign*outward;path.lineTo(x,startY+deltaY*.34);path.bezierCurveTo(x+depth,startY+deltaY*.34,x+depth,startY+deltaY*.66,x,startY+deltaY*.66);path.lineTo(x,startY+deltaY);}
function piecePath(piece){const path=new Path2D(),width=board.cellWidth,height=board.cellHeight;path.moveTo(0,0);horizontalEdge(path,0,0,width,piece.edges.top,-1);verticalEdge(path,width,0,height,piece.edges.right,1);horizontalEdge(path,width,height,-width,piece.edges.bottom,1);verticalEdge(path,0,height,-height,piece.edges.left,-1);path.closePath();return path;}
function pieceIsEdge(piece){return!piece.edges.top||!piece.edges.right||!piece.edges.bottom||!piece.edges.left;}
function groupPieces(groupId){return pieces.filter((piece)=>piece.groupId===groupId);}
function selectedPieces(){return selectedGroupId===null?[]:groupPieces(selectedGroupId);}

function perimeterSlots(){
  const count=activePieceCount,topCount=Math.max(2,Math.ceil(count*.3)),bottomCount=Math.max(2,Math.floor(count*.3)),sideTotal=count-topCount-bottomCount,leftCount=Math.ceil(sideTotal/2),rightCount=sideTotal-leftCount,halfW=board.cellWidth*trayScale/2,halfH=board.cellHeight*trayScale/2;
  const spread=(amount,start,end)=>Array.from({length:amount},(_value,index)=>amount===1?(start+end)/2:start+(end-start)*index/(amount-1));const topY=Math.max(halfH+72,board.y-halfH-22),bottomY=Math.min(puzzleWorkAreaBottom()-halfH-18,board.y+board.height+halfH+22),leftX=Math.max(halfW+8,board.x-halfW-20),rightX=Math.min(canvas.width-halfW-8,board.x+board.width+halfW+20),slots=[];
  spread(topCount,halfW+12,canvas.width-halfW-12).forEach((x)=>slots.push({x,y:topY,zone:"top"}));spread(rightCount,board.y+halfH,board.y+board.height-halfH).forEach((y)=>slots.push({x:rightX,y,zone:"right"}));spread(bottomCount,canvas.width-halfW-12,halfW+12).forEach((x)=>slots.push({x,y:bottomY,zone:"bottom"}));spread(leftCount,board.y+board.height-halfH,board.y+halfH).forEach((y)=>slots.push({x:leftX,y,zone:"left"}));return slots;
}
function deterministicShuffle(values){const out=[...values];resetCampaignRandom();for(let index=out.length-1;index>0;index-=1){const swapIndex=Math.floor(campaignRandom()*(index+1));[out[index],out[swapIndex]]=[out[swapIndex],out[index]];}return out;}
function createPieces(){
  pieces=[];groupSequence=0;for(let row=0;row<rows;row+=1)for(let column=0;column<columns;column+=1)pieces.push({index:pieces.length,row,column,homeX:board.x+(column+.5)*board.cellWidth,homeY:board.y+(row+.5)*board.cellHeight,x:0,y:0,angle:rotationEnabled?Math.floor(campaignRandom()*4)*Math.PI/2:0,edges:edgesFor(row,column),groupId:groupSequence++,locked:false,displayScale:trayScale,bounceUntil:0});
  const slots=deterministicShuffle(perimeterSlots());pieces.forEach((piece,index)=>{const slot=slots[index];piece.x=slot.x;piece.y=slot.y;piece.zone=slot.zone;});validation=validatePuzzleGeometry();
}
function validatePuzzleGeometry(){let complementary=true;pieces.forEach((piece)=>{const right=pieces.find((candidate)=>candidate.row===piece.row&&candidate.column===piece.column+1),bottom=pieces.find((candidate)=>candidate.row===piece.row+1&&candidate.column===piece.column);if(right&&piece.edges.right!==-right.edges.left)complementary=false;if(bottom&&piece.edges.bottom!==-bottom.edges.top)complementary=false;});const outsideCount=pieces.filter((piece)=>piece.x<board.x||piece.x>board.x+board.width||piece.y<board.y||piece.y>board.y+board.height).length,centers=new Set(pieces.map((piece)=>piece.x.toFixed(2)+":"+piece.y.toFixed(2)));return{pieceProduct:columns*rows,complementary,outsideCount,uniqueCenters:centers.size};}

function worldTransform(){ctx.translate(canvas.width/2+viewPan.x,canvas.height/2+viewPan.y);ctx.scale(viewScale,viewScale);ctx.translate(-canvas.width/2,-canvas.height/2);}
function screenToWorld(point){return{x:(point.x-canvas.width/2-viewPan.x)/viewScale+canvas.width/2,y:(point.y-canvas.height/2-viewPan.y)/viewScale+canvas.height/2};}
function resetPuzzleView(){viewScale=1;viewPan={x:0,y:0};}
function setPuzzleZoom(next){viewScale=Math.max(1,Math.min(2.1,next));if(viewScale===1)viewPan={x:0,y:0};setStatus("画板缩放 "+Math.round(viewScale*100)+"%；拖动画板空白处可平移。");drawPuzzle();}
function drawTrayRails(){ctx.save();ctx.strokeStyle="rgba(104,91,82,.2)";ctx.lineWidth=2;ctx.setLineDash([8,12]);const gap=14;ctx.strokeRect(gap,Math.max(gap,board.y-board.cellHeight*trayScale-42),canvas.width-gap*2,Math.min(board.cellHeight*trayScale+32,board.y-gap*2));ctx.strokeRect(gap,board.y+board.height+10,canvas.width-gap*2,Math.max(34,puzzleWorkAreaBottom()-board.y-board.height-gap-10));ctx.strokeRect(gap,board.y,Math.max(32,board.x-gap-10),board.height);ctx.strokeRect(board.x+board.width+10,board.y,Math.max(32,canvas.width-board.x-board.width-gap-10),board.height);ctx.restore();}
function drawBoardGuide(timestamp){
  drawPlayfield(board.x-14,board.y-14,board.width+28,board.height+28,{radius:22,alpha:.94,fill:"rgba(255,253,248,.96)",stroke:"rgba(95,84,75,.34)",lineWidth:3});ctx.save();ctx.beginPath();ctx.rect(board.x,board.y,board.width,board.height);ctx.clip();ctx.globalAlpha=Math.max(.035,puzzleBlueprint().guideOpacity||config.puzzleRules?.guideOpacity||.14);ctx.drawImage(image,board.x,board.y,board.width,board.height);ctx.restore();
  ctx.save();ctx.strokeStyle="rgba(95,84,75,.18)";ctx.lineWidth=1;for(let column=1;column<columns;column+=1){ctx.beginPath();ctx.moveTo(board.x+column*board.cellWidth,board.y);ctx.lineTo(board.x+column*board.cellWidth,board.y+board.height);ctx.stroke();}for(let row=1;row<rows;row+=1){ctx.beginPath();ctx.moveTo(board.x,board.y+row*board.cellHeight);ctx.lineTo(board.x+board.width,board.y+row*board.cellHeight);ctx.stroke();}ctx.restore();
  if(hintPieceIndex>=0&&timestamp<hintUntil){const piece=pieces[hintPieceIndex],pulse=.55+.25*Math.sin(timestamp/100);ctx.save();ctx.strokeStyle="rgba(236,137,105,"+pulse+")";ctx.lineWidth=6;ctx.strokeRect(piece.homeX-board.cellWidth/2,piece.homeY-board.cellHeight/2,board.cellWidth,board.cellHeight);ctx.restore();}
}
function drawPiece(piece,timestamp){
  if(!visibleWorkshopPiece(piece)&&piece.groupId!==selectedGroupId)return;const selected=piece.groupId===selectedGroupId,scale=selected?1:piece.displayScale,bounce=piece.bounceUntil>timestamp?Math.sin((piece.bounceUntil-timestamp)*.09)*7:0;
  ctx.save();ctx.translate(piece.x+bounce,piece.y);ctx.rotate(piece.angle);ctx.scale(scale,scale);ctx.translate(-board.cellWidth/2,-board.cellHeight/2);const path=piecePath(piece);ctx.shadowColor=selected?"rgba(88,69,59,.34)":"rgba(68,54,45,.2)";ctx.shadowBlur=selected?16:7;ctx.shadowOffsetY=selected?8:4;ctx.save();ctx.clip(path);ctx.drawImage(image,-piece.column*board.cellWidth,-piece.row*board.cellHeight,board.width,board.height);if(piece.locked){ctx.fillStyle="rgba(255,255,255,.025)";ctx.fill(path);}ctx.restore();ctx.shadowColor="transparent";ctx.strokeStyle=selected?"#e46f72":piece.locked?"rgba(255,255,255,.78)":"rgba(80,69,61,.62)";ctx.lineWidth=(selected?4:2.4)/Math.max(.55,scale);ctx.stroke(path);if(timestamp<connectionPulseUntil&&selected){ctx.strokeStyle="rgba(255,211,118,.9)";ctx.lineWidth=7;ctx.globalAlpha=Math.max(0,(connectionPulseUntil-timestamp)/260);ctx.stroke(path);}ctx.restore();
}
function drawPreviewOverlay(timestamp){if(timestamp>=previewUntil)return;const remaining=previewUntil-timestamp,alpha=Math.min(1,(timestamp-previewStartedAt)/180,remaining/220)*.96;ctx.save();ctx.fillStyle="rgba(247,243,238,"+(alpha*.88)+")";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.globalAlpha=alpha;drawPlayfield(board.x-18,board.y-18,board.width+36,board.height+36,{radius:24,alpha:1,fill:"#fff",stroke:"rgba(82,71,63,.48)",lineWidth:3});ctx.drawImage(image,board.x,board.y,board.width,board.height);ctx.fillStyle="#4e443f";ctx.font="700 18px Inter,Microsoft YaHei,sans-serif";ctx.textAlign="center";ctx.fillText("完成图预览",canvas.width/2,Math.max(34,board.y-32));ctx.restore();}
function drawPauseOverlay(){if(!puzzlePaused)return;ctx.save();ctx.fillStyle="rgba(248,245,240,.86)";ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle="#4d443f";ctx.textAlign="center";ctx.font="700 38px Inter,Microsoft YaHei,sans-serif";ctx.fillText("拼图暂停",canvas.width/2,canvas.height*.48);ctx.font="500 18px Inter,Microsoft YaHei,sans-serif";ctx.fillText("按 P、空格或继续返回",canvas.width/2,canvas.height*.53);ctx.restore();}
function drawCompletion(timestamp){if(timestamp>=completionUntil)return;const alpha=Math.max(0,Math.min(1,(completionUntil-timestamp)/220));ctx.save();ctx.globalAlpha=.95;ctx.drawImage(image,board.x,board.y,board.width,board.height);ctx.strokeStyle="rgba(255,218,128,"+alpha+")";ctx.lineWidth=10;ctx.shadowColor="#ffe0a6";ctx.shadowBlur=24;ctx.strokeRect(board.x,board.y,board.width,board.height);ctx.restore();}
function drawPuzzle(timestamp=performance.now()){clearPuzzleCanvas();if(!image.naturalWidth)return;ctx.save();worldTransform();drawTrayRails();drawBoardGuide(timestamp);pieces.filter((piece)=>piece.locked).forEach((piece)=>drawPiece(piece,timestamp));pieces.filter((piece)=>!piece.locked&&piece.groupId!==selectedGroupId).forEach((piece)=>drawPiece(piece,timestamp));selectedPieces().forEach((piece)=>drawPiece(piece,timestamp));drawPreviewOverlay(timestamp);drawPauseOverlay();drawCompletion(timestamp);ctx.restore();drawWorkshopGuide();finishCanvasStyle();}
function drawPreview(){clearPuzzleCanvas();if(!image.naturalWidth)return;drawPlayfield(board.x-18,board.y-18,board.width+36,board.height+36,{radius:24,alpha:.96,fill:"#fff",stroke:"rgba(93,80,71,.38)",lineWidth:3});ctx.drawImage(image,board.x,board.y,board.width,board.height);finishCanvasStyle();}

function inversePiecePoint(piece,x,y,scale){const dx=(x-piece.x)/scale,dy=(y-piece.y)/scale,cos=Math.cos(-piece.angle),sin=Math.sin(-piece.angle);return{x:dx*cos-dy*sin+board.cellWidth/2,y:dx*sin+dy*cos+board.cellHeight/2};}
function findPieceAt(x,y){for(let index=pieces.length-1;index>=0;index-=1){const piece=pieces[index];if(piece.locked||(!visibleWorkshopPiece(piece)&&piece.groupId!==selectedGroupId))continue;const scale=piece.groupId===selectedGroupId?1:piece.displayScale,point=inversePiecePoint(piece,x,y,scale);if(ctx.isPointInPath(piecePath(piece),point.x,point.y))return piece;}return null;}
function translateGroup(groupId,dx,dy){groupPieces(groupId).forEach((piece)=>{piece.x+=dx;piece.y+=dy;piece.displayScale=1;});}
function normalizeAngle(value){const full=Math.PI*2;let angle=value%full;if(angle<0)angle+=full;return Math.abs(angle-full)<.001?0:angle;}
function rotateSelectedGroup(){if(!rotationEnabled||selectedGroupId===null||puzzlePaused)return false;const group=selectedPieces();if(!group.length||group.some((piece)=>piece.locked))return false;const cx=group.reduce((sum,piece)=>sum+piece.x,0)/group.length,cy=group.reduce((sum,piece)=>sum+piece.y,0)/group.length;group.forEach((piece)=>{const dx=piece.x-cx,dy=piece.y-cy;piece.x=cx-dy;piece.y=cy+dx;piece.angle=normalizeAngle(piece.angle+Math.PI/2);});moves+=1;playSound("ui");setStatus("已旋转当前拼块组；回到正向后才能与相邻块连接。");persistPuzzleSession();drawPuzzle();return true;}
function neighborPieces(piece){return pieces.filter((candidate)=>Math.abs(candidate.row-piece.row)+Math.abs(candidate.column-piece.column)===1);}
function mergeGroups(sourceId,targetId){if(sourceId===targetId)return;pieces.forEach((piece)=>{if(piece.groupId===sourceId)piece.groupId=targetId;});selectedGroupId=targetId;connectionCount+=1;connectionPulseUntil=performance.now()+260;playSound("success");}
function tryConnectSelected(){if(selectedGroupId===null)return false;let connected=false,searching=true;while(searching){searching=false;const source=selectedPieces();for(const piece of source){if(Math.abs(normalizeAngle(piece.angle))>.001)continue;for(const neighbor of neighborPieces(piece)){if(neighbor.groupId===selectedGroupId||Math.abs(normalizeAngle(neighbor.angle))>.001)continue;const expectedX=piece.x+(neighbor.column-piece.column)*board.cellWidth,expectedY=piece.y+(neighbor.row-piece.row)*board.cellHeight,distance=Math.hypot(neighbor.x-expectedX,neighbor.y-expectedY),tolerance=Math.min(board.cellWidth,board.cellHeight)*.27;if(distance>tolerance)continue;translateGroup(selectedGroupId,neighbor.x-expectedX,neighbor.y-expectedY);const sourceId=selectedGroupId;mergeGroups(sourceId,neighbor.groupId);connected=true;searching=true;break;}if(searching)break;}}return connected;}
function lockGroupAtHome(){if(selectedGroupId===null)return false;const group=selectedPieces();if(!group.length||group.some((piece)=>Math.abs(normalizeAngle(piece.angle))>.001))return false;let anchor=null,distance=Infinity;group.forEach((piece)=>{const next=Math.hypot(piece.x-piece.homeX,piece.y-piece.homeY);if(next<distance){distance=next;anchor=piece;}});const tolerance=Math.min(board.cellWidth,board.cellHeight)*(config.puzzleRules?config.puzzleRules.snapTolerance:.26);if(!anchor||distance>tolerance)return false;translateGroup(selectedGroupId,anchor.homeX-anchor.x,anchor.homeY-anchor.y);if(!group.every((piece)=>Math.hypot(piece.x-piece.homeX,piece.y-piece.homeY)<1.5))return false;group.forEach((piece)=>{piece.x=piece.homeX;piece.y=piece.homeY;piece.locked=true;piece.displayScale=1;});placedCount=pieces.filter((piece)=>piece.locked).length;connectionPulseUntil=performance.now()+300;playSound("reward");persistPuzzleSession();return true;}
function completePuzzle(){completionUntil=performance.now()+1100;const token=++completionToken;setGameSessionState("stage-complete");clearPuzzleSession();drawPuzzle();window.setTimeout(()=>{if(token!==completionToken)return;const elapsed=Math.max(1,Math.round(elapsedActiveMs/1000));showResult(true,"画面完整重现",puzzleBlueprint().name+"完成 · "+columns+" × "+rows+" · "+moves+" 次移动 · "+connectionCount+" 次拼合 · "+bounceCount+" 次错位 · "+hintsUsed+" 次目标提示 · "+elapsed+" 秒有效拼合 · "+puzzleWorkshopProgress(pieces,rows,columns).regions.filter((r)=>r.total&&r.done===r.total).length+" 个区域还原。");},850);}
function releaseSelectedGroup(){if(selectedGroupId===null)return;moves+=1;const connected=tryConnectSelected(),locked=lockGroupAtHome();if(locked){setMetric(placedCount+" / "+pieces.length);setStatus("整组归位："+placedCount+" / "+pieces.length+"。相邻拼块可以先在外围拼合，再整体放回画板。");if(placedCount===pieces.length){completePuzzle();return;}}else if(connected)setStatus("拼缝已连接；当前组包含 "+selectedPieces().length+" 块，可以整体移动。");else if(puzzleDropIsBoardAttempt(selectedPieces(),board)){selectedPieces().forEach((piece)=>{piece.bounceUntil=performance.now()+230;});bounceCount+=1;playSound("illegal");setStatus("画板上还没有对齐；试着找直边或连接相邻纹理，也可以查看线索。");}else setStatus("已放到外围工作台。自由整理不算错位，可以继续接成小组。");workshopHintIndex=-1;persistPuzzleSession();syncPuzzleControls();drawPuzzle();}

canvas.addEventListener("pointerdown",(event)=>{if(!running||puzzlePaused)return;const screen=eventCanvasPoint(event),world=screenToWorld(screen),hit=findPieceAt(world.x,world.y);if(hit){selectedGroupId=hit.groupId;selectedPieces().forEach((piece)=>{piece.displayScale=1;});dragState={pointerId:event.pointerId,last:world,moved:0};canvas.setPointerCapture(event.pointerId);playSound("move");drawPuzzle();return;}selectedGroupId=null;if(viewScale>1){panState={pointerId:event.pointerId,last:screen};canvas.setPointerCapture(event.pointerId);}drawPuzzle();});
canvas.addEventListener("pointermove",(event)=>{const screen=eventCanvasPoint(event);if(dragState&&dragState.pointerId===event.pointerId){const world=screenToWorld(screen),dx=world.x-dragState.last.x,dy=world.y-dragState.last.y;translateGroup(selectedGroupId,dx,dy);dragState.moved+=Math.hypot(dx,dy);dragState.last=world;drawPuzzle();return;}if(panState&&panState.pointerId===event.pointerId){viewPan.x+=screen.x-panState.last.x;viewPan.y+=screen.y-panState.last.y;panState.last=screen;drawPuzzle();}});
function completePuzzleDrag(moved){if(moved<7&&rotationEnabled)rotateSelectedGroup();else{if(moved>=7)signalOnboarding("piece-dragged");releaseSelectedGroup();}}
function releasePuzzlePointer(event){if(dragState&&dragState.pointerId===event.pointerId){const moved=dragState.moved;dragState=null;completePuzzleDrag(moved);}panState=null;if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId);}
canvas.addEventListener("pointerup",releasePuzzlePointer);canvas.addEventListener("pointercancel",releasePuzzlePointer);canvas.addEventListener("wheel",(event)=>{if(!running||puzzlePaused)return;event.preventDefault();setPuzzleZoom(viewScale+(event.deltaY<0?.15:-.15));},{passive:false});

function arrangePuzzlePieces(){if(!running||puzzlePaused)return false;const slots=deterministicShuffle(perimeterSlots()),movable=pieces.filter((piece)=>!piece.locked&&groupPieces(piece.groupId).length===1);movable.forEach((piece,index)=>{const slot=slots[index%slots.length];piece.x=slot.x;piece.y=slot.y;piece.zone=slot.zone;piece.displayScale=trayScale;});for(const groupId of new Set(pieces.filter((p)=>!p.locked&&groupPieces(p.groupId).length>1).map((p)=>p.groupId))){const group=groupPieces(groupId),shift=puzzleRecoverGroupOffset(group,board,{left:12,right:canvas.width-12,top:74,bottom:puzzleWorkAreaBottom()-12});translateGroup(groupId,shift.dx,shift.dy);}selectedGroupId=null;resetPuzzleView();setStatus("单块已整理到外围，越界拼块组已整体收回；不会拆散拼好的组。");playSound("ui");persistPuzzleSession();drawPuzzle();return true;}
function toggleEdgePieces(){if(!running||puzzlePaused)return false;edgeOnly=!edgeOnly;regionFilter="all";document.querySelectorAll("[data-control=edge]").forEach((button)=>{button.textContent=edgeOnly?"显示全部":"只看边块";button.setAttribute("aria-pressed",String(edgeOnly));});selectedGroupId=null;setStatus(edgeOnly?"只看边块及与它相连的整组；不会拆散已拼好的部分。":"已恢复显示全部拼块。");syncPuzzleControls();persistPuzzleSession();drawPuzzle();return true;}
function showPuzzlePreview(){if(!running||puzzlePaused)return false;previewStartedAt=performance.now();previewUntil=previewStartedAt+1450;playSound("ui");setStatus("完成图会短暂淡入，拼块位置与进度不会改变。");drawPuzzle();return true;}
function showPuzzleHint(){if(!running||puzzlePaused)return false;const candidate=selectedPieces().find((p)=>!p.locked)||pieces.find((p)=>!p.locked&&visibleWorkshopPiece(p))||pieces.find((p)=>!p.locked);if(!candidate)return false;selectedGroupId=candidate.groupId;if(workshopHintIndex!==candidate.index){workshopHintIndex=candidate.index;const straight=Object.values(candidate.edges).filter((v)=>v===0).length;setStatus((straight>=2?"两条直边相遇，这是角块。":straight===1?"有一条直边，先对照画面外围。":"没有直边，先寻找画面内部的连续纹理。")+" 它来自画面"+["上部","中部","下部"][puzzleRegion(candidate.row,rows)]+(candidate.angle?"；当前还需转正。":"。")+(hintsRemaining?" 再按一次线索可显示目标，不自动代拼。":" 目标提示已用完，仍可免费预览和查看线索。"));syncPuzzleControls();drawPuzzle();return true;}if(hintsRemaining<=0){workshopHintIndex=-1;return showPuzzleHint();}hintsRemaining-=1;hintsUsed+=1;hintPieceIndex=candidate.index;hintUntil=performance.now()+2200;workshopHintIndex=-1;syncPuzzleControls();persistPuzzleSession();playSound("ui");setStatus("已标出这块的位置，请自己拖放；剩余 "+hintsRemaining+" 次目标提示。");drawPuzzle();return true;}
function togglePuzzlePause(){if(gameSessionState==="playing"){puzzlePaused=true;setGameSessionState("paused");stopEnvironmentAudio();setStatus("拼图已暂停；返回后由你主动继续。");}else if(gameSessionState==="paused"){puzzlePaused=false;setGameSessionState("playing");lastFrameAt=performance.now();startAmbient();setStatus(puzzleBlueprint().name+"继续。");}syncPuzzleControls();drawPuzzle();}
function syncPuzzleControls(){document.querySelectorAll("[data-puzzle-region]").forEach((input)=>{input.value=regionFilter;input.disabled=puzzlePaused||gameSessionState!=="playing";});document.querySelectorAll("[data-control=edge]").forEach((button)=>{button.textContent=edgeOnly?"显示全部":"只看边块";button.setAttribute("aria-pressed",String(edgeOnly));});document.querySelectorAll("[data-control]").forEach((button)=>{if(button.dataset.control==="pause")button.disabled=!(gameSessionState==="playing"||gameSessionState==="paused");});document.querySelectorAll("[data-control=pause]").forEach((button)=>{button.textContent=puzzlePaused?"继续":"暂停";});document.querySelectorAll("[data-control=hint]").forEach((button)=>{button.textContent=(workshopHintIndex>=0&&hintsRemaining?"看位置 ":"线索 ")+hintsRemaining;button.disabled=puzzlePaused||gameSessionState!=="playing";});document.querySelectorAll("[data-control=rotate]").forEach((button)=>{button.disabled=puzzlePaused||!rotationEnabled||gameSessionState!=="playing";});}
function clearPuzzleSession(){try{safeStorage.removeItem(puzzleSessionKey());}catch{}}
function persistPuzzleSession(){if(puzzleImageLoading||activeLevelId==="custom"||!pieces.length||!["playing","paused"].includes(gameSessionState))return;try{safeStorage.setItem(puzzleSessionKey(),JSON.stringify({schemaVersion:3,level:currentCampaignLevel().number,imageLevel:activeLevelId,pieceCount:activePieceCount,mode:puzzleMode,rotation:rotationEnabled,locked:pieces.filter((piece)=>piece.locked).map((piece)=>piece.index),layout:pieces.map((p)=>({index:p.index,x:(p.x-board.x)/board.cellWidth,y:(p.y-board.y)/board.cellHeight,turn:Math.round(normalizeAngle(p.angle)/(Math.PI/2))%4,groupId:p.groupId,locked:p.locked,displayScale:p.displayScale})),regionFilter,edgeOnly,elapsedActiveMs,remainingMs,moves,bounceCount,connectionCount,hintsRemaining,hintsUsed,updatedAt:new Date().toISOString()}));}catch{}}
function restorePuzzleSession(){restoredPieces=0;restoredGroups=0;if(activeLevelId==="custom")return;try{const saved=JSON.parse(safeStorage.getItem(puzzleSessionKey())||"null");if(!saved||![2,3].includes(saved.schemaVersion)||saved.level!==currentCampaignLevel().number||saved.imageLevel!==activeLevelId||saved.pieceCount!==activePieceCount||saved.mode!==puzzleMode||saved.rotation!==rotationEnabled)return;const expanded=Array.isArray(saved.layout)?saved.layout.map((p)=>({...p,x:board.x+p.x*board.cellWidth,y:board.y+p.y*board.cellHeight})):null;const layout=saved.schemaVersion===3?puzzleValidatedLayout(expanded,pieces,board,canvas.width,canvas.height):null;if(layout){layout.forEach((entry)=>{const piece=pieces[entry.index];piece.x=entry.x;piece.y=entry.y;piece.angle=entry.turn*Math.PI/2;piece.groupId=entry.groupId;piece.locked=entry.locked;piece.displayScale=entry.locked||layout.filter((p)=>p.groupId===entry.groupId).length>1?1:entry.displayScale??trayScale;});restoredGroups=new Set(pieces.filter((p)=>!p.locked&&groupPieces(p.groupId).length>1).map((p)=>p.groupId)).size;}else{const locked=new Set(Array.isArray(saved.locked)?saved.locked.filter((n)=>Number.isInteger(n)&&n>=0&&n<pieces.length):[]);pieces.filter((p)=>locked.has(p.index)).forEach((p)=>{p.x=p.homeX;p.y=p.homeY;p.angle=0;p.locked=true;p.displayScale=1;p.groupId=-1;});}placedCount=pieces.filter((p)=>p.locked).length;restoredPieces=placedCount;const count=(value,max=1000000)=>Number.isFinite(value)?Math.max(0,Math.min(max,Math.floor(value))):0;moves=count(saved.moves);bounceCount=count(saved.bounceCount);connectionCount=count(saved.connectionCount);hintsRemaining=count(saved.hintsRemaining,puzzleBlueprint().hintUses);hintsUsed=count(saved.hintsUsed);if(saved.schemaVersion===3){elapsedActiveMs=count(saved.elapsedActiveMs,86400000);remainingMs=Number.isFinite(saved.remainingMs)?Math.max(0,Math.min(timeLimitMs,saved.remainingMs)):timeLimitMs;regionFilter=["all","0","1","2"].includes(saved.regionFilter)?saved.regionFilter:"all";edgeOnly=Boolean(saved.edgeOnly);}}catch{}}

function startGame(){
  if(puzzleImageLoading||!image.naturalWidth||!image.naturalHeight){pendingPuzzleRestart=true;setStatus("图片仍在载入，完成后会自动开始。");return;}pendingPuzzleRestart=false;completionToken+=1;resetCampaignRandom();rotationEnabled=Boolean(rotationInput?.checked);puzzleMode=modeButtons.find((button)=>button.classList.contains("is-selected"))?.dataset.puzzleMode||"classic";gridForImage();layoutBoard();createPieces();placedCount=0;moves=0;bounceCount=0;connectionCount=0;hintsRemaining=puzzleBlueprint().hintUses;hintsUsed=0;hintPieceIndex=-1;hintUntil=0;previewUntil=0;completionUntil=0;selectedGroupId=null;dragState=null;panState=null;edgeOnly=currentCampaignLevel().number>=13;regionFilter="all";workshopHintIndex=-1;elapsedActiveMs=0;restoredGroups=0;puzzlePaused=false;resetPuzzleView();timeLimitMs=puzzleMode==="timed"?Math.max(90000,(puzzleBlueprint().challengeSeconds||activePieceCount*6)*1000):0;remainingMs=timeLimitMs;startedAt=performance.now();lastFrameAt=startedAt;lastTimerSecond=-1;restorePuzzleSession();hideOverlay();setMetric(placedCount+" / "+pieces.length);setStatus("第 "+currentCampaignLevel().number+" 关 · "+puzzleBlueprint().name+" · "+pieces.length+" 块；拼块已整理在画板四周"+(restoredPieces||restoredGroups?"，恢复 "+restoredPieces+" 块归位、"+restoredGroups+" 个拼块组":"")+"。");startAmbient();syncPuzzleControls();drawPuzzle();
}
function loadPuzzleImage(level,shouldRestart){if(!level||level.id==="custom")return;activeLevelId=level.id;syncInputs(levelInputs,activeLevelId);const requestId=beginPuzzleImageLoad(),nextImage=new Image();nextImage.addEventListener("load",()=>{if(requestId!==puzzleImageRequestId)return;image=nextImage;setPuzzleImageLoading(false);gridForImage();layoutBoard();const settled=["won","stage-complete","lost"].includes(gameSessionState),shouldResume=(shouldRestart||pendingPuzzleRestart)&&!settled;pendingPuzzleRestart=false;if(shouldResume)startGame();else if(settled)drawPuzzle();else{drawPreview();setStatus("已选择 "+level.label+" · "+activePieceCount+" 块。");}});nextImage.src=level.path;}
function applyPuzzleCampaignLevel(level){const allowed=config.puzzleRules?.allowedPieceCounts||[6,9,12,16,20,24,30,36,42,48,50];activePieceCount=allowed.includes(puzzleBlueprint().pieceCount)?puzzleBlueprint().pieceCount:allowed[Math.min(allowed.length-1,Math.floor((level.number-1)/2))];syncInputs(pieceCountInputs,activePieceCount);if(activeLevelId==="custom")return;const builtIns=config.imageLevels.filter((candidate)=>candidate.id!=="custom"),next=builtIns[(level.number-1)%builtIns.length];if(next&&next.id!==activeLevelId)loadPuzzleImage(next,false);}
onCampaignLevelChanged=applyPuzzleCampaignLevel;
restartCurrentGame=()=>{clearPuzzleSession();setGameSessionState("restarting");startGame();};

pieceCountInputs.forEach((input)=>input.addEventListener("change",()=>{activePieceCount=Number(input.value);syncInputs(pieceCountInputs,activePieceCount);clearPuzzleSession();if(running)startGame();else setStatus("已选择 "+activeLevelLabel()+" · "+activePieceCount+" 块。开始后拼块会整理在画板四周。 ");}));
levelInputs.forEach((input)=>input.addEventListener("change",()=>{const next=config.imageLevels.find((level)=>level.id===input.value);if(!next||next.id==="custom")return;clearPuzzleSession();loadPuzzleImage(next,running);}));
modeButtons.forEach((button)=>button.addEventListener("click",()=>{modeButtons.forEach((candidate)=>{const selected=candidate===button;candidate.classList.toggle("is-selected",selected);candidate.setAttribute("aria-pressed",String(selected));});clearPuzzleSession();}));rotationInput?.addEventListener("change",clearPuzzleSession);

const uploadInput=document.querySelector("#puzzle-upload");
if(uploadInput)uploadInput.addEventListener("change",(event)=>{const file=event.target.files&&event.target.files[0];if(!file||!file.type.startsWith("image/")){setStatus("请选择 PNG、JPEG 或 WebP 图片。");return;}if(file.size>12*1024*1024){setStatus("图片超过 12MB，请先缩小文件后再试。");return;}const reader=new FileReader();reader.addEventListener("load",()=>{const requestId=beginPuzzleImageLoad(),nextImage=new Image();nextImage.addEventListener("load",()=>{if(requestId!==puzzleImageRequestId)return;if(nextImage.naturalWidth<200||nextImage.naturalHeight<200){setPuzzleImageLoading(false);setStatus("图片边长至少需要 200 像素，避免拼块模糊。");return;}image=nextImage;setPuzzleImageLoading(false);activeLevelId="custom";if(!config.imageLevels.some((level)=>level.id==="custom")){config.imageLevels.unshift({id:"custom",label:"我的图片",path:""});levelInputs.forEach((input)=>input.add(new Option("我的图片","custom",true,true),0));}syncInputs(levelInputs,activeLevelId);document.querySelector("#upload-name").textContent=file.name+" · "+image.naturalWidth+"×"+image.naturalHeight;clearPuzzleSession();startGame();});nextImage.src=String(reader.result);});reader.readAsDataURL(file);});

function selectNextPuzzlePiece(){const available=pieces.filter((piece)=>!piece.locked&&visibleWorkshopPiece(piece));if(!available.length)return false;const current=available.findIndex((piece)=>piece.groupId===selectedGroupId),next=available[(current+1+available.length)%available.length];selectedGroupId=next.groupId;selectedPieces().forEach((piece)=>{piece.displayScale=1;});setStatus("已选择第 "+(next.index+1)+" 块；方向键移动，Enter 尝试连接或归位。");drawPuzzle();return true;}
function moveSelected(dx,dy){if(selectedGroupId===null)selectNextPuzzlePiece();if(selectedGroupId===null)return;translateGroup(selectedGroupId,dx,dy);drawPuzzle();}
function handleControl(value){if(value==="zoom-in")setPuzzleZoom(viewScale+.2);else if(value==="zoom-out")setPuzzleZoom(viewScale-.2);else if(value==="arrange")arrangePuzzlePieces();else if(value==="edge")toggleEdgePieces();else if(value==="preview")showPuzzlePreview();else if(value==="hint")showPuzzleHint();else if(value==="rotate")rotateSelectedGroup();else if(value==="pause")togglePuzzlePause();}
function handleKey(key){const normalized=key.length===1?key.toLowerCase():key;if(normalized==="p"||key===" "){togglePuzzlePause();return;}if(!running||puzzlePaused)return;if(key==="Tab"){selectNextPuzzlePiece();return;}if(normalized==="h"){showPuzzleHint();return;}if(normalized==="r"){rotateSelectedGroup();return;}if(normalized==="+"){setPuzzleZoom(viewScale+.2);return;}if(normalized==="-"){setPuzzleZoom(viewScale-.2);return;}if(normalized==="v"){showPuzzlePreview();return;}const step=Math.max(7,Math.min(board.cellWidth,board.cellHeight)*.15);if(key==="ArrowLeft")moveSelected(-step,0);if(key==="ArrowRight")moveSelected(step,0);if(key==="ArrowUp")moveSelected(0,-step);if(key==="ArrowDown")moveSelected(0,step);if(key==="Enter"&&selectedGroupId!==null)releaseSelectedGroup();}
function puzzleAnimationLoop(timestamp){const delta=lastFrameAt?Math.min(100,timestamp-lastFrameAt):0;if(running&&!puzzlePaused)elapsedActiveMs+=delta;if(running&&!puzzlePaused&&timeLimitMs){remainingMs=Math.max(0,remainingMs-delta);const second=Math.ceil(remainingMs/1000);if(second!==lastTimerSecond){lastTimerSecond=second;setMetric(placedCount+" / "+pieces.length+" · "+second+"s");}if(remainingMs<=0){showResult(false,"限时挑战结束",puzzleBlueprint().name+"还差 "+(pieces.length-placedCount)+" 块；经典模式没有倒计时，也可以减少拼块数量后重试。");syncPuzzleControls();}}lastFrameAt=timestamp;if(running||puzzlePaused||timestamp<hintUntil||timestamp<previewUntil||timestamp<connectionPulseUntil||timestamp<completionUntil)drawPuzzle(timestamp);requestAnimationFrame(puzzleAnimationLoop);}
document.addEventListener("visibilitychange",()=>{if(document.hidden&&gameSessionState==="playing"){persistPuzzleSession();togglePuzzlePause();}});window.addEventListener("pagehide",persistPuzzleSession);

runtimeDebugActions={
  neighborProbe(){for(const first of pieces.filter((p)=>!p.locked&&p.angle===0&&visibleWorkshopPiece(p))){for(const neighbor of neighborPieces(first).filter((p)=>!p.locked&&p.angle===0&&p.groupId!==first.groupId&&visibleWorkshopPiece(p))){const to={x:neighbor.x-(neighbor.column-first.column)*board.cellWidth,y:neighbor.y-(neighbor.row-first.row)*board.cellHeight};if(to.x<board.cellWidth/2||to.x>canvas.width-board.cellWidth/2||to.y<board.cellHeight/2+70||to.y>puzzleWorkAreaBottom()-board.cellHeight/2)continue;return {from:{x:first.x,y:first.y},to,first:first.index,neighbor:neighbor.index,canvas:{width:canvas.width,height:canvas.height}};}}return null;},
  pointerProbe(){const piece=pieces.find((candidate)=>!candidate.locked);return piece?{from:{x:piece.x,y:piece.y},to:{x:piece.homeX,y:piece.homeY},canvas:{width:canvas.width,height:canvas.height}}:null;},
  dragFirstPiece(){const piece=pieces.find((candidate)=>!candidate.locked);if(!piece)return false;selectedGroupId=piece.groupId;translateGroup(selectedGroupId,12,0);completePuzzleDrag(12);return true;},
  selectNext:selectNextPuzzlePiece,
  placeSelectedAtHome(){if(selectedGroupId===null)selectNextPuzzlePiece();const group=selectedPieces();if(!group.length)return false;group.forEach((piece)=>{piece.angle=0;});const anchor=group[0];translateGroup(selectedGroupId,anchor.homeX-anchor.x,anchor.homeY-anchor.y);releaseSelectedGroup();return true;},
  connectPair(){const first=pieces.find((piece)=>!piece.locked),neighbor=first&&neighborPieces(first).find((piece)=>!piece.locked);if(!first||!neighbor)return false;selectedGroupId=first.groupId;first.angle=0;neighbor.angle=0;first.x=neighbor.x-(neighbor.column-first.column)*board.cellWidth;first.y=neighbor.y-(neighbor.row-first.row)*board.cellHeight;releaseSelectedGroup();return groupPieces(neighbor.groupId).length>=2;},
  arrange:arrangePuzzlePieces,hint:showPuzzleHint,preview:showPuzzlePreview,zoomIn:()=>setPuzzleZoom(1.6),pause:togglePuzzlePause,
  forceTimeout(){puzzleMode="timed";timeLimitMs=1000;remainingMs=0;lastFrameAt=performance.now();},
};
runtimeDebugState=()=>({workshop:{regionFilter,progress:puzzleWorkshopProgress(pieces,rows,columns),lesson:puzzleWorkshopLesson(currentCampaignLevel().number,puzzleWorkshopProgress(pieces,rows,columns),connectionCount),restoredGroups,elapsedActiveMs,hintStage:workshopHintIndex>=0?"reason":"ready",pieces:pieces.map((p)=>({index:p.index,x:p.x,y:p.y,homeX:p.homeX,homeY:p.homeY,row:p.row,column:p.column,groupId:p.groupId,angle:p.angle,locked:p.locked,visible:visibleWorkshopPiece(p)}))},level:currentCampaignLevel().number,levelName:puzzleBlueprint().name,chapter:puzzleBlueprint().chapter,imageLevel:activeLevelId,imageLevelCount:config.imageLevels.length,pieceCount:activePieceCount,grid:{columns,rows,product:columns*rows},placedCount,moves,bounceCount,connectionCount,groupCount:new Set(pieces.filter((piece)=>!piece.locked).map((piece)=>piece.groupId)).size,largestGroup:Math.max(0,...Array.from(new Set(pieces.map((piece)=>piece.groupId))).map((id)=>groupPieces(id).length)),boardAspect:Number((board.width/board.height).toFixed(3)),imageAspect:image.naturalWidth?Number((image.naturalWidth/image.naturalHeight).toFixed(3)):0,boardRect:{x:Math.round(board.x),y:Math.round(board.y),width:Math.round(board.width),height:Math.round(board.height)},perimeterZones:4,trayScale:Number(trayScale.toFixed(3)),outsideCount:validation?.outsideCount||0,uniqueCenters:validation?.uniqueCenters||0,complementaryEdges:Boolean(validation?.complementary),clickPlacement:true,keyboardPlacement:true,groupMovement:true,zoom:viewScale,panEnabled:viewScale>1,edgeOnly,rotationEnabled,puzzleMode,paused:puzzlePaused,hintsRemaining,hintsUsed,previewActive:performance.now()<previewUntil,snapFeedback:connectionPulseUntil>performance.now(),restoredPieces,timeRemaining:Math.ceil(remainingMs/1000),uploadAdaptive:true});

syncInputs(pieceCountInputs,activePieceCount);syncInputs(levelInputs,activeLevelId);const initialImageRequestId=beginPuzzleImageLoad();image.addEventListener("load",()=>{if(initialImageRequestId!==puzzleImageRequestId)return;setPuzzleImageLoading(false);gridForImage();layoutBoard();drawPreview();setStatus("已选择 "+activeLevelLabel()+" · "+activePieceCount+" 块。");});image.src=config.imagePath;requestAnimationFrame(puzzleAnimationLoop);
`;
