import { usePreferences, type ResolvedLocale } from "./preferences";
import { designKnowledgeForms, type DesignKnowledgeFormKey } from "./DesignKnowledgeConsole.forms-copy";
import { designKnowledgeExtraCopy, designKnowledgeExtraKeys, type DesignKnowledgeExtraKey } from "./DesignKnowledgeConsole.extra-copy";

const zhCN = {
  "common.cancel":"取消","common.save":"保存","common.loading":"正在读取设计证据…","common.error":"操作没有完成。","common.versionError":"服务数据版本不一致，请刷新页面或重新启动本地服务。","common.previous":"上一页","common.next":"下一页","common.none":"没有匹配结果","common.count":"{count} 项","common.signals":"{count} 条信号","common.reviews":"{count} 个复核期",
  "main.documentTitle":"策划知识发布台 · 造界","main.defaultTitle":"造界 · AI 游戏工坊","main.eyebrow":"内部策划 · 版本化知识","main.title":"把试玩证据变成下一版设计能力","main.detail":"系统只提出建议。真人试玩、人工决定和独立审核齐全后，新的玩法等级才会影响之后创建的游戏。","main.flow":"知识更新流程","main.stage":"阶段 {number}","main.playtests":"真人试玩","main.quarterly":"季度复核","main.changes":"版本变更","main.releases":"知识发布",
  "radar.formLabel":"登记玩法信号","radar.formEyebrow":"市场观察，不是采用结论","radar.title":"先发现变化，再决定是否研究","radar.eyebrow":"玩法雷达","radar.detail":"跨榜同名项目自动合并；过期信号会提醒复核。这里的任何内容都不会直接进入正式玩法库。","radar.add":"登记信号","radar.empty":"暂无市场信号。登记官方榜单、开发者更新或社区排名后，系统会归并并检查近邻。","radar.game":"游戏名称","radar.sourceTitle":"来源标题","radar.sourceUrl":"来源网址","radar.sourceType":"来源类型","radar.platform":"平台","radar.observed":"观察日期","radar.published":"发布日期（可选）","radar.summary":"可核验的热度或评选事实","radar.verbs":"玩家动作（逗号分隔）","radar.tags":"机制标签（逗号分隔）","radar.save":"保存信号","radar.sites":"{count} 个独立站点","radar.validUntil":"有效至 {date}","radar.linked":"已关联 {count} 次研究","radar.unresearched":"尚未研究","radar.merge":"合并建议","radar.neighbor":"已知近邻","radar.independent":"独立研究","radar.reresearch":"重新研究","radar.mergeExisting":"合并到现有研究","radar.continue":"继续研究","radar.enter":"进入研究","radar.fresh":"新鲜","radar.aging":"即将复核","radar.stale":"需要更新",
  "radar.editorial":"编辑榜单","radar.award":"年度奖项","radar.store":"商店排名","radar.developer":"开发者更新","radar.community":"社区排名","radar.cross":"跨平台","radar.web":"网页","radar.mobile":"手机","radar.desktop":"桌面","atlas.family.movement":"移动","atlas.family.spatial":"空间","atlas.family.matching":"匹配","atlas.family.economy":"经济","atlas.family.combat":"战斗","atlas.family.collection":"收集","atlas.family.construction":"建造","atlas.family.information":"信息","atlas.family.timing":"时机","atlas.family.social":"社会模拟","atlas.family.progression":"成长","atlas.family.risk":"风险回报","atlas.family.physics":"物理","atlas.family.stealth":"潜行","atlas.family.narrative":"叙事","atlas.family.simulation":"模拟","atlas.family.strategy":"策略","atlas.family.survival":"生存","atlas.family.multiplayer":"多人","atlas.family.creation":"创作","atlas.eyebrow":"独立机制库","atlas.title":"{count} 张独立机制卡","atlas.detail":"每张卡只表示一个玩家动作、状态变化和可观察结果。设计修饰器与组合配方分开保存，不计入机制数量。","atlas.mechanics":"独立机制","atlas.modifiers":"设计修饰器","atlas.search":"搜索","atlas.placeholder":"例如：旋转、侦察、立即重试","atlas.family":"机制领域","atlas.all":"全部领域","atlas.submit":"检索","atlas.found":"找到 {matched} 张 · 已索引本地资料 {indexed} 份","atlas.card":"独立机制","atlas.state":"状态变化","atlas.rule":"制作规则","atlas.acceptance":"验收信号","atlas.footer":"参考候选 · 需要原型验证",
  "insights.eyebrow":"跨周期证据","insights.title":"趋势与试玩细分","insights.select":"查看玩法","insights.latest":"最新完成率","insights.needPeriods":"至少两个复核期后显示变化","insights.rise":"上升","insights.fall":"下降","insights.points":"{count} 个百分点","insights.completion":"完成率","insights.exit":"退出率","insights.empty":"生成复核快照后显示跨周期变化。","insights.playtest":"真人试玩切片","insights.records":"{count} 次结构化记录","insights.onboarding":"教学","insights.controls":"操作","insights.fun":"趣味","insights.fairness":"公平","insights.experience":"玩家经验","insights.device":"设备","insights.input":"输入方式","insights.noPlaytest":"记录真人试玩后显示细分对比。","insights.summary":"{count} 次 · 完成 {completion}","insights.replay":"重玩 {replay} · 趣味 {fun}",
} as const;
type BaseKey = keyof typeof zhCN;
type Key = BaseKey | DesignKnowledgeFormKey | DesignKnowledgeExtraKey;
type Table = Record<BaseKey,string>;

const zhTW: Table = {
  "common.cancel":"取消","common.save":"儲存","common.loading":"正在讀取設計證據…","common.error":"操作未完成。","common.versionError":"服務資料版本不一致，請重新整理頁面或重新啟動本機服務。","common.previous":"上一頁","common.next":"下一頁","common.none":"沒有符合結果","common.count":"{count} 項","common.signals":"{count} 條信號","common.reviews":"{count} 個複核期",
  "main.documentTitle":"策劃知識發佈台 · 造界","main.defaultTitle":"造界 · AI 遊戲工坊","main.eyebrow":"內部策劃 · 版本化知識","main.title":"把試玩證據變成下一版設計能力","main.detail":"系統只提出建議。真人試玩、人工決定和獨立審核齊全後，新的玩法等級才會影響之後建立的遊戲。","main.flow":"知識更新流程","main.stage":"階段 {number}","main.playtests":"真人試玩","main.quarterly":"季度複核","main.changes":"版本變更","main.releases":"知識發佈",
  "radar.formLabel":"登記玩法信號","radar.formEyebrow":"市場觀察，不是採用結論","radar.title":"先發現變化，再決定是否研究","radar.eyebrow":"玩法雷達","radar.detail":"跨榜同名項目會自動合併；過期信號會提醒複核。這裡的內容不會直接進入正式玩法庫。","radar.add":"登記信號","radar.empty":"暫無市場信號。登記官方榜單、開發者更新或社群排名後，系統會合併並檢查近鄰。","radar.game":"遊戲名稱","radar.sourceTitle":"來源標題","radar.sourceUrl":"來源網址","radar.sourceType":"來源類型","radar.platform":"平台","radar.observed":"觀察日期","radar.published":"發佈日期（選填）","radar.summary":"可核驗的熱度或評選事實","radar.verbs":"玩家動作（逗號分隔）","radar.tags":"機制標籤（逗號分隔）","radar.save":"儲存信號","radar.sites":"{count} 個獨立站點","radar.validUntil":"有效至 {date}","radar.linked":"已關聯 {count} 次研究","radar.unresearched":"尚未研究","radar.merge":"合併建議","radar.neighbor":"已知近鄰","radar.independent":"獨立研究","radar.reresearch":"重新研究","radar.mergeExisting":"合併到現有研究","radar.continue":"繼續研究","radar.enter":"進入研究","radar.fresh":"新鮮","radar.aging":"即將複核","radar.stale":"需要更新",
  "radar.editorial":"編輯榜單","radar.award":"年度獎項","radar.store":"商店排名","radar.developer":"開發者更新","radar.community":"社群排名","radar.cross":"跨平台","radar.web":"網頁","radar.mobile":"手機","radar.desktop":"桌面","atlas.family.movement":"移動","atlas.family.spatial":"空間","atlas.family.matching":"配對","atlas.family.economy":"經濟","atlas.family.combat":"戰鬥","atlas.family.collection":"收集","atlas.family.construction":"建造","atlas.family.information":"資訊","atlas.family.timing":"時機","atlas.family.social":"社會模擬","atlas.family.progression":"成長","atlas.family.risk":"風險回報","atlas.family.physics":"物理","atlas.family.stealth":"潛行","atlas.family.narrative":"敘事","atlas.family.simulation":"模擬","atlas.family.strategy":"策略","atlas.family.survival":"生存","atlas.family.multiplayer":"多人","atlas.family.creation":"創作","atlas.eyebrow":"獨立機制庫","atlas.title":"{count} 張獨立機制卡","atlas.detail":"每張卡只表示一個玩家動作、狀態變化和可觀察結果。設計修飾器與組合配方分開保存，不計入機制數量。","atlas.mechanics":"獨立機制","atlas.modifiers":"設計修飾器","atlas.search":"搜尋","atlas.placeholder":"例如：旋轉、偵察、立即重試","atlas.family":"機制領域","atlas.all":"全部領域","atlas.submit":"搜尋","atlas.found":"找到 {matched} 張 · 已索引本機資料 {indexed} 份","atlas.card":"獨立機制","atlas.state":"狀態變化","atlas.rule":"製作規則","atlas.acceptance":"驗收信號","atlas.footer":"參考候選 · 需要原型驗證",
  "insights.eyebrow":"跨週期證據","insights.title":"趨勢與試玩細分","insights.select":"查看玩法","insights.latest":"最新完成率","insights.needPeriods":"至少兩個複核期後顯示變化","insights.rise":"上升","insights.fall":"下降","insights.points":"{count} 個百分點","insights.completion":"完成率","insights.exit":"退出率","insights.empty":"生成複核快照後顯示跨週期變化。","insights.playtest":"真人試玩切片","insights.records":"{count} 次結構化記錄","insights.onboarding":"教學","insights.controls":"操作","insights.fun":"趣味","insights.fairness":"公平","insights.experience":"玩家經驗","insights.device":"裝置","insights.input":"輸入方式","insights.noPlaytest":"記錄真人試玩後顯示細分比較。","insights.summary":"{count} 次 · 完成 {completion}","insights.replay":"重玩 {replay} · 趣味 {fun}",
};
const en: Table = {
  "common.cancel":"Cancel","common.save":"Save","common.loading":"Loading design evidence…","common.error":"The operation did not complete.","common.versionError":"The service data version does not match. Refresh the page or restart the local service.","common.previous":"Previous","common.next":"Next","common.none":"No matching results","common.count":"{count} items","common.signals":"{count} signals","common.reviews":"{count} review periods",
  "main.documentTitle":"Design Knowledge Console · PlayForge","main.defaultTitle":"PlayForge · AI Game Studio","main.eyebrow":"Internal design · Versioned knowledge","main.title":"Turn playtest evidence into the next design capability","main.detail":"The system only proposes changes. New gameplay levels affect future games after playtests, human decisions, and independent review are complete.","main.flow":"Knowledge update flow","main.stage":"Stage {number}","main.playtests":"Playtests","main.quarterly":"Quarterly review","main.changes":"Version changes","main.releases":"Knowledge releases",
  "radar.formLabel":"Record gameplay signal","radar.formEyebrow":"Market observation, not an adoption decision","radar.title":"Detect change before deciding what to research","radar.eyebrow":"Gameplay radar","radar.detail":"Matching titles across lists are merged and stale signals prompt review. Nothing here enters the published gameplay library directly.","radar.add":"Record signal","radar.empty":"No market signals yet. Add official lists, developer updates, or community rankings to group and compare signals.","radar.game":"Game title","radar.sourceTitle":"Source title","radar.sourceUrl":"Source URL","radar.sourceType":"Source type","radar.platform":"Platform","radar.observed":"Observed date","radar.published":"Published date (optional)","radar.summary":"Verifiable popularity or selection fact","radar.verbs":"Player actions (comma-separated)","radar.tags":"Mechanic tags (comma-separated)","radar.save":"Save signal","radar.sites":"{count} independent sites","radar.validUntil":"Valid until {date}","radar.linked":"Linked to {count} studies","radar.unresearched":"Not researched","radar.merge":"Merge suggestion","radar.neighbor":"Known neighbor","radar.independent":"Independent study","radar.reresearch":"Research again","radar.mergeExisting":"Merge into existing study","radar.continue":"Continue research","radar.enter":"Start research","radar.fresh":"Fresh","radar.aging":"Review soon","radar.stale":"Update needed",
  "radar.editorial":"Editorial list","radar.award":"Annual award","radar.store":"Store ranking","radar.developer":"Developer update","radar.community":"Community ranking","radar.cross":"Cross-platform","radar.web":"Web","radar.mobile":"Mobile","radar.desktop":"Desktop","atlas.family.movement":"Movement","atlas.family.spatial":"Spatial","atlas.family.matching":"Matching","atlas.family.economy":"Economy","atlas.family.combat":"Combat","atlas.family.collection":"Collection","atlas.family.construction":"Construction","atlas.family.information":"Information","atlas.family.timing":"Timing","atlas.family.social":"Social simulation","atlas.family.progression":"Progression","atlas.family.risk":"Risk and reward","atlas.family.physics":"Physics","atlas.family.stealth":"Stealth","atlas.family.narrative":"Narrative","atlas.family.simulation":"Simulation","atlas.family.strategy":"Strategy","atlas.family.survival":"Survival","atlas.family.multiplayer":"Multiplayer","atlas.family.creation":"Creation","atlas.eyebrow":"Independent mechanic library","atlas.title":"{count} independent mechanic cards","atlas.detail":"Each card represents one player action, state change, and observable result. Modifiers and recipes are stored separately and do not count as mechanics.","atlas.mechanics":"Independent mechanics","atlas.modifiers":"Design modifiers","atlas.search":"Search","atlas.placeholder":"For example: rotate, scout, retry instantly","atlas.family":"Mechanic family","atlas.all":"All families","atlas.submit":"Search","atlas.found":"Found {matched} · {indexed} local sources indexed","atlas.card":"Independent mechanic","atlas.state":"State change","atlas.rule":"Production rule","atlas.acceptance":"Acceptance signal","atlas.footer":"Reference candidate · Prototype validation required",
  "insights.eyebrow":"Evidence across periods","insights.title":"Trends and playtest segments","insights.select":"View gameplay","insights.latest":"Latest completion rate","insights.needPeriods":"Change appears after at least two review periods","insights.rise":"Up","insights.fall":"Down","insights.points":"{count} percentage points","insights.completion":"Completion","insights.exit":"Exit","insights.empty":"Create review snapshots to show changes across periods.","insights.playtest":"Playtest segments","insights.records":"{count} structured records","insights.onboarding":"Onboarding","insights.controls":"Controls","insights.fun":"Fun","insights.fairness":"Fairness","insights.experience":"Player experience","insights.device":"Device","insights.input":"Input","insights.noPlaytest":"Record playtests to show segment comparisons.","insights.summary":"{count} plays · {completion} complete","insights.replay":"Replay {replay} · Fun {fun}",
};
const ja: Table = {
  "common.cancel":"キャンセル","common.save":"保存","common.loading":"設計エビデンスを読み込み中…","common.error":"操作を完了できませんでした。","common.versionError":"サービスのデータ版が一致しません。ページを更新するかローカルサービスを再起動してください。","common.previous":"前へ","common.next":"次へ","common.none":"一致する結果はありません","common.count":"{count} 件","common.signals":"{count} 件の信号","common.reviews":"{count} 回の審査期間",
  "main.documentTitle":"企画ナレッジ公開台 · 遊造","main.defaultTitle":"遊造 · AIゲーム工房","main.eyebrow":"内部企画 · バージョン管理された知識","main.title":"試遊エビデンスを次の設計能力へ","main.detail":"システムは提案のみを行います。試遊、担当者の判断、独立審査が揃ってから、新しいゲームプレイ評価が今後のゲームに反映されます。","main.flow":"知識更新フロー","main.stage":"段階 {number}","main.playtests":"試遊","main.quarterly":"四半期審査","main.changes":"バージョン変更","main.releases":"知識公開",
  "radar.formLabel":"ゲームプレイ信号を登録","radar.formEyebrow":"市場観察であり、採用判断ではありません","radar.title":"変化を見つけてから調査を判断","radar.eyebrow":"ゲームプレイレーダー","radar.detail":"複数ランキングの同名項目を統合し、古い信号は再確認を促します。ここから正式ライブラリへ直接追加されることはありません。","radar.add":"信号を登録","radar.empty":"市場信号はまだありません。公式リスト、開発者更新、コミュニティ順位を登録すると近い項目をまとめます。","radar.game":"ゲーム名","radar.sourceTitle":"情報源のタイトル","radar.sourceUrl":"情報源URL","radar.sourceType":"情報源の種類","radar.platform":"プラットフォーム","radar.observed":"観察日","radar.published":"公開日（任意）","radar.summary":"確認可能な人気・選出の事実","radar.verbs":"プレイヤー行動（カンマ区切り）","radar.tags":"メカニクスタグ（カンマ区切り）","radar.save":"信号を保存","radar.sites":"独立サイト {count} 件","radar.validUntil":"有効期限 {date}","radar.linked":"{count} 件の調査に関連","radar.unresearched":"未調査","radar.merge":"統合候補","radar.neighbor":"既知の近似","radar.independent":"独立調査","radar.reresearch":"再調査","radar.mergeExisting":"既存調査に統合","radar.continue":"調査を続行","radar.enter":"調査を開始","radar.fresh":"新規","radar.aging":"まもなく再確認","radar.stale":"更新が必要",
  "radar.editorial":"編集ランキング","radar.award":"年間賞","radar.store":"ストア順位","radar.developer":"開発者更新","radar.community":"コミュニティ順位","radar.cross":"クロスプラットフォーム","radar.web":"Web","radar.mobile":"モバイル","radar.desktop":"デスクトップ","atlas.family.movement":"移動","atlas.family.spatial":"空間","atlas.family.matching":"マッチング","atlas.family.economy":"経済","atlas.family.combat":"戦闘","atlas.family.collection":"収集","atlas.family.construction":"建造","atlas.family.information":"情報","atlas.family.timing":"タイミング","atlas.family.social":"社会シミュレーション","atlas.family.progression":"成長","atlas.family.risk":"リスクと報酬","atlas.family.physics":"物理","atlas.family.stealth":"潜行","atlas.family.narrative":"物語","atlas.family.simulation":"シミュレーション","atlas.family.strategy":"戦略","atlas.family.survival":"サバイバル","atlas.family.multiplayer":"マルチプレイ","atlas.family.creation":"創作","atlas.eyebrow":"独立メカニクス庫","atlas.title":"独立メカニクスカード {count} 枚","atlas.detail":"各カードは一つのプレイヤー行動、状態変化、観察可能な結果を表します。修飾子と組み合わせは別管理で、メカニクス数に含みません。","atlas.mechanics":"独立メカニクス","atlas.modifiers":"設計修飾子","atlas.search":"検索","atlas.placeholder":"例：回転、偵察、すぐ再挑戦","atlas.family":"メカニクス領域","atlas.all":"すべての領域","atlas.submit":"検索","atlas.found":"{matched} 枚 · ローカル資料 {indexed} 件を索引済み","atlas.card":"独立メカニクス","atlas.state":"状態変化","atlas.rule":"制作ルール","atlas.acceptance":"検収信号","atlas.footer":"参考候補 · プロトタイプ検証が必要",
  "insights.eyebrow":"期間横断エビデンス","insights.title":"傾向と試遊セグメント","insights.select":"ゲームプレイを表示","insights.latest":"最新完了率","insights.needPeriods":"2回以上の審査期間後に変化を表示","insights.rise":"上昇","insights.fall":"低下","insights.points":"{count} ポイント","insights.completion":"完了率","insights.exit":"離脱率","insights.empty":"審査スナップショットを作成すると期間ごとの変化を表示します。","insights.playtest":"試遊セグメント","insights.records":"構造化記録 {count} 件","insights.onboarding":"導入","insights.controls":"操作","insights.fun":"楽しさ","insights.fairness":"公平性","insights.experience":"プレイヤー経験","insights.device":"端末","insights.input":"入力方法","insights.noPlaytest":"試遊を記録するとセグメント比較を表示します。","insights.summary":"{count} 回 · 完了 {completion}","insights.replay":"再プレイ {replay} · 楽しさ {fun}",
};

const tables: Record<ResolvedLocale,Table> = { "zh-CN":zhCN,"zh-TW":zhTW,en,ja };
export type DesignKnowledgeCopyKey = Key;
export const designKnowledgeCopyKeys = [...Object.keys(zhCN), ...Object.keys(designKnowledgeForms), ...designKnowledgeExtraKeys] as Key[];
export function designKnowledgeCopy(locale: ResolvedLocale, key: Key, values: Record<string,string|number> = {}) {
  const localeIndex = { "zh-CN":0,"zh-TW":1,en:2,ja:3 }[locale];
  const formCopy = designKnowledgeForms[key as DesignKnowledgeFormKey];
  const source = formCopy ? formCopy[localeIndex] : key in tables[locale] ? tables[locale][key as BaseKey] : designKnowledgeExtraCopy(locale,key as DesignKnowledgeExtraKey);
  return Object.entries(values).reduce((text,[name,value]) => text.replaceAll(`{${name}}`,String(value)),source);
}
export function useDesignKnowledgeCopy() {
  const { locale } = usePreferences();
  return (key: Key, values: Record<string,string|number> = {}) => designKnowledgeCopy(locale,key,values);
}

