import type { ResolvedLocale } from "./preferences";

const zhCN = {
  failureReason: "失败原因", affectedNext: "请查看上方的受影响资源和下一步。", noFailureDetail: "这份历史构建记录没有保存详细原因。",
  autoCheck: "自动检查：{quality} · 人工美术审核：{art}", passed: "通过", failed: "未通过", pending: "尚未完成", artPassed: "有通过记录", artPending: "待审核",
  formalReview: "正式复核由平台审核端完成。你可以直接试玩和提出修改，无需自行填写专业审核结论。",
  failedWithSteps: "制作未完成；请按已列出的下一步处理后再明确提交。", stoppedPlayable: "本轮制作已停止；上一个成功版本仍可试玩。",
  reviewLoadFailed: "暂时无法读取试玩验收状态。", reviewSaveFailed: "试玩验收没有保存，请稍后重试。", reviewLabel: "试玩验收状态", reviewed: "当前试玩版已验收", reviewFirst: "请先试玩当前版本", reviewedDetail: "你现在可以在下方明确提出一项可选调整，例如风格、底图、色调、难度或增加关卡。系统不会自动执行建议。", reviewDetail: "可以直接反馈错误或复刻差异。增加关卡、难度、等级等扩展，需要你先试玩并明确验收当前版本。", reviewSaving: "正在保存验收…", reviewApprove: "我已试玩，验收通过",
  workspace: "你的作品空间", playModify: "试玩 · 修改", progress: "当前进展", stoppingTitle: "正在停止这轮制作…", loadingTitle: "正在读取你的游戏…", readyTitle: "游戏已准备好，先玩一局吧。", failedTitle: "本次制作未完成，已有成功版本不会被覆盖。", stoppedTitle: "本轮制作已停止，已有成功版本不会被覆盖。", runningTitle: "正在把修改做进游戏。", queuedTitle: "修改已收到，等待开始制作。", idleTitle: "从这份方案继续制作。", stoppingDetail: "正在等待服务端确认；确认前不会把它显示为已停止。", stoppedDetail: "已停止后续制作；已发出的远程请求已尝试中止，但服务商可能已开始计费。", runningDetail: "服务端正在处理，无需重复提交。", idleDetail: "先试玩，再告诉我们哪里还可以更好。每次修改都沿用这个作品。",
  retry: "重新制作", retryButton: "手动重新制作", retryDetail: "只在上方原因明确可重试时提供此操作；会开始一轮新的制作并使用模型用量。", stopping: "正在停止…", stop: "停止制作", recent: "最近的修改意见", full: "查看完整方案、制作与审核记录", fullDetail: "以下为专业制作详情。实际审核仍按原有标准执行，不以展开或关闭记录代替审核。", modify: "修改游戏", actionFallback: "本次操作没有被确认。当前记录保持不变；请按错误提示决定是否手动重试。",
} as const;
type Key = keyof typeof zhCN;
const tables: Record<ResolvedLocale, Record<Key, string>> = {
  "zh-CN": zhCN,
  "zh-TW": { failureReason: "失敗原因", affectedNext: "請查看上方受影響的資源與下一步。", noFailureDetail: "這份歷史構建記錄沒有保存詳細原因。", autoCheck: "自動檢查：{quality} · 人工美術審核：{art}", passed: "通過", failed: "未通過", pending: "尚未完成", artPassed: "有通過記錄", artPending: "待審核", formalReview: "正式複核由平台審核端完成。你可以直接試玩和提出修改，無需自行填寫專業審核結論。", failedWithSteps: "製作未完成；請按已列出的下一步處理後再明確提交。", stoppedPlayable: "本輪製作已停止；上一個成功版本仍可試玩。", reviewLoadFailed: "暫時無法讀取試玩驗收狀態。", reviewSaveFailed: "試玩驗收未保存，請稍後重試。", reviewLabel: "試玩驗收狀態", reviewed: "目前試玩版已驗收", reviewFirst: "請先試玩目前版本", reviewedDetail: "你現在可以在下方明確提出一項可選調整，例如風格、底圖、色調、難度或增加關卡。系統不會自動執行建議。", reviewDetail: "可以直接回報錯誤或復刻差異。增加關卡、難度、等級等擴展，需要先試玩並明確驗收目前版本。", reviewSaving: "正在保存驗收…", reviewApprove: "我已試玩，驗收通過", workspace: "你的作品空間", playModify: "試玩 · 修改", progress: "目前進展", stoppingTitle: "正在停止本輪製作…", loadingTitle: "正在讀取你的遊戲…", readyTitle: "遊戲已準備好，先玩一局吧。", failedTitle: "本次製作未完成，已有成功版本不會被覆蓋。", stoppedTitle: "本輪製作已停止，已有成功版本不會被覆蓋。", runningTitle: "正在把修改做進遊戲。", queuedTitle: "修改已收到，等待開始製作。", idleTitle: "從這份方案繼續製作。", stoppingDetail: "正在等待服務端確認；確認前不會顯示為已停止。", stoppedDetail: "已停止後續製作；已發出的遠端請求已嘗試中止，但服務商可能已開始計費。", runningDetail: "服務端正在處理，無需重複提交。", idleDetail: "先試玩，再告訴我們哪裡還可以更好。每次修改都沿用這個作品。", retry: "重新製作", retryButton: "手動重新製作", retryDetail: "只在上方原因明確可重試時提供；會開始新一輪製作並使用模型用量。", stopping: "正在停止…", stop: "停止製作", recent: "最近的修改意見", full: "查看完整方案、製作與審核記錄", fullDetail: "以下為專業製作詳情。實際審核仍按原有標準執行，不以展開或關閉記錄代替審核。", modify: "修改遊戲", actionFallback: "本次操作未確認。目前記錄保持不變；請按錯誤提示決定是否手動重試。" },
  en: { failureReason: "Failure reason", affectedNext: "See the affected resources and next step above.", noFailureDetail: "This historical build did not retain detailed failure information.", autoCheck: "Automated checks: {quality} · Art review: {art}", passed: "Passed", failed: "Failed", pending: "Not completed", artPassed: "Passed record", artPending: "Pending", formalReview: "Formal review is completed by the platform review team. You can play and request changes without recording a professional review yourself.", failedWithSteps: "The build did not finish. Follow the listed next step before submitting again.", stoppedPlayable: "This build stopped; the previous successful version remains playable.", reviewLoadFailed: "The play-review status is temporarily unavailable.", reviewSaveFailed: "The play review was not saved. Try again later.", reviewLabel: "Play-review status", reviewed: "Current preview reviewed", reviewFirst: "Play the current version first", reviewedDetail: "You can now request an optional change below, such as style, background, tone, difficulty, or more levels. Suggestions are not applied automatically.", reviewDetail: "You can report bugs or remake differences immediately. Extensions such as levels, difficulty, or ranks require playing and explicitly approving the current version first.", reviewSaving: "Saving review…", reviewApprove: "I played it and approve", workspace: "Your project space", playModify: "Play · Edit", progress: "Current progress", stoppingTitle: "Stopping this build…", loadingTitle: "Loading your game…", readyTitle: "Your game is ready. Play a round first.", failedTitle: "This build did not finish. Existing successful versions are preserved.", stoppedTitle: "This build stopped. Existing successful versions are preserved.", runningTitle: "Applying your changes to the game.", queuedTitle: "Changes received and waiting to build.", idleTitle: "Continue from this plan.", stoppingDetail: "Waiting for server confirmation; it will not appear stopped until confirmed.", stoppedDetail: "Further work stopped. Sent remote requests were cancelled where possible, but the provider may already have begun billing.", runningDetail: "The server is processing this request; do not submit it again.", idleDetail: "Play first, then tell us what could improve. Every change stays with this project.", retry: "Rebuild", retryButton: "Rebuild manually", retryDetail: "Available only when the reason above is explicitly retryable. This starts a new build and uses model quota.", stopping: "Stopping…", stop: "Stop build", recent: "Recent change notes", full: "View full plan, build, and review record", fullDetail: "The professional build details follow. Reviews still use the established standards; opening or closing this record does not replace review.", modify: "Edit game", actionFallback: "This action was not confirmed. Current records remain unchanged; follow the error guidance before deciding whether to retry manually." },
  ja: { failureReason: "失敗理由", affectedNext: "上にある影響対象と次の手順を確認してください。", noFailureDetail: "この過去のビルドには詳しい失敗理由が保存されていません。", autoCheck: "自動チェック：{quality} · アート確認：{art}", passed: "合格", failed: "不合格", pending: "未完了", artPassed: "合格記録あり", artPending: "確認待ち", formalReview: "正式確認はプラットフォームの審査側で行います。専門的な審査結果を自分で入力せず、直接プレイして変更を依頼できます。", failedWithSteps: "制作は完了していません。表示された次の手順を実行してから再度送信してください。", stoppedPlayable: "今回の制作は停止しました。前回の成功版は引き続きプレイできます。", reviewLoadFailed: "試遊確認の状態を一時的に読み込めません。", reviewSaveFailed: "試遊確認を保存できませんでした。後でもう一度お試しください。", reviewLabel: "試遊確認の状態", reviewed: "現在の試遊版は確認済み", reviewFirst: "まず現在のバージョンをプレイしてください", reviewedDetail: "下から、スタイル、背景、色調、難易度、ステージ追加など任意の変更を明示できます。提案が自動実行されることはありません。", reviewDetail: "不具合や再現差をすぐ報告できます。ステージ、難易度、ランクなどの拡張は、現在版を試して明示的に承認してから行えます。", reviewSaving: "確認を保存中…", reviewApprove: "プレイして確認しました", workspace: "作品スペース", playModify: "試す · 編集", progress: "現在の進行", stoppingTitle: "今回の制作を停止中…", loadingTitle: "ゲームを読み込み中…", readyTitle: "ゲームの準備ができました。まず1回遊んでみましょう。", failedTitle: "今回の制作は完了していません。既存の成功版は保持されています。", stoppedTitle: "今回の制作は停止しました。既存の成功版は保持されています。", runningTitle: "変更をゲームに反映しています。", queuedTitle: "変更を受け付け、制作開始を待っています。", idleTitle: "この案から制作を続けます。", stoppingDetail: "サーバーの確認を待っています。確認されるまで停止済みとは表示しません。", stoppedDetail: "以降の制作を停止しました。送信済みのリモート要求は可能な限り中止しましたが、提供元で課金が始まっている場合があります。", runningDetail: "サーバーで処理中です。重複して送信しないでください。", idleDetail: "まずプレイし、改善したい点を伝えてください。変更はすべてこの作品に引き継がれます。", retry: "再制作", retryButton: "手動で再制作", retryDetail: "上の理由が明確に再試行可能な場合だけ利用できます。新しい制作を開始し、モデル利用枠を消費します。", stopping: "停止中…", stop: "制作を停止", recent: "最近の変更メモ", full: "完全な計画・制作・確認記録を表示", fullDetail: "以下は専門的な制作詳細です。実際の確認は従来の基準で行い、この記録の開閉で代替しません。", modify: "ゲームを編集", actionFallback: "この操作は確定されませんでした。現在の記録は変わりません。エラーの案内に従い、手動で再試行するか判断してください。" },
};

export function projectCopy(locale: ResolvedLocale, key: Key, values: Record<string, string | number> = {}) {
  return Object.entries(values).reduce((text, [name, value]) => text.replaceAll(`{${name}}`, String(value)), tables[locale][key]);
}
